- id: '1613686499118'
  alias: Tvonwhenasleep
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.easleep
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    entity_id: media_player.bedroom
  mode: single
