automation:
  - alias: styrbarremote
    id: styrbarremote
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: ikea_styrbar
    action:
      - variables:
          button: "{{trigger.event.data.event}}"
          up: 1002
          down: 2002
          left: 3002
          right: 4002
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ button == up}}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.office_full
          - conditions:
              - condition: template
                value_template: "{{ button == down}}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.office_off
          - conditions:
              - condition: template
                value_template: "{{ button == left}}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.office_default
          - conditions:
              - condition: template
                value_template: "{{ button == right}}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.office_default
        default:
          - service: script.telegram_notify
            data:
              message: Triggered unregistered event on Styrbar remote {{trigger.event.data.event}}"

            # ***1 n책r man holder, ***3 n책r man slipper.
            # kan rolig incremente p책 noe vis da muligens i en while loop, og stoppe n책r slipp kommer?
