#works, but we have tibber, so.
# - platform: integration
#   source: sensor.pulse_power
#   name: energy_spent
#   unit_prefix: k
#   round: 2

- platform: rest
  name: TSLA
  scan_interval: 120
  json_attributes:
    - o
    - h
    - i
    - pc
    - t
  resource: https://finnhub.io/api/v1/quote?symbol=TSLA&token=bpt70g7rh5r8muvsh2f0
  value_template: "{{ value_json.c }}"
  force_update: true
  unit_of_measurement: USD

- platform: rest
  name: PLTR
  scan_interval: 120
  json_attributes:
    - o
    - h
    - i
    - pc
    - t
  resource: https://finnhub.io/api/v1/quote?symbol=PLTR&token=bpt70g7rh5r8muvsh2f0
  value_template: "{{ value_json.c }}"
  force_update: true
  unit_of_measurement: USD

# - platform: rest
#   name: GME
#   scan_interval: 5
#   json_attributes:
#   resource: https://query2.finance.yahoo.com/v10/finance/quoteSummary/GME?formatted=true&crumb=8ldhetOu7RJ&lang=en-US&region=US&modules=defaultKeyStatistics%2CfinancialData%2CcalendarEvents&corsDomain=finance.yahoo.com
#   value_template: "{{ value_json.quoteSummary.result[0].financialData.currentPrice.raw }}"
#   force_update: true
#   unit_of_measurement: USD

# - platform: scrape
#   name: 'THETA'
#   resource: 'https://coinmarketcap.com/currencies/theta/'
#   select: 'div.priceValue___11gHJ'
#   value_template: "{{value.split('$')[1] | float}}"
#   unit_of_measurement: USD

# - platform: command_line
#   command: 'curl -X GET -H "Content-type: application/json" -H "kp-api-token: {{states.sensor.postenapikey.state}}"  https://www.posten.no/levering-av-post/_/service/no.posten.website/delivery-days?postalCode=7072'
#   name: MailToday
#   json_attributes:
#     - nextDeliveryDays
#   value_template: "{{'i dag' in (value_json.nextDeliveryDays | string) }}"
#   scan_interval: 57600
#   command_timeout: 30

# - platform: template
#   sensors:
#     date:
#       friendly_name: 'Date'
#       value_template: '{{ states.sensor.json_time.attributes["date"] }}'
#     milliseconds:
#       friendly_name: 'milliseconds'
#       value_template: '{{ states.sensor.json_time.attributes["milliseconds_since_epoch"] }}'

# - platform: alpha_vantage
#   api_key: !secret alpha_vantage
#   symbols:
#     - symbol: TSLA
#       name: Tesla
#     # - symbol: TSLA
#     #   name: Tesla NOK
#     #   currency: NOK
#   foreign_exchange:
#     - name: USD_NOK
#       from: USD
#       to: NOK

# - platform: google_wifi
#   host: 192.168.1.1

# - platform: wasteplan_trv
#   id: 1035
#   pickup_day: 1

# - platform: darksky
#   api_key: !secret darksky_api_key
#   forecast:
#     - 0
#     - 1
#   hourly_forecast:
#     - 8
#   monitored_conditions:
#     - summary
#     - precip_type
#     - precip_intensity
#     - precip_probability
#     - temperature
#     - dew_point
#     - wind_speed
#     - wind_bearing
#     - cloud_cover
#     - humidity
#     - pressure
#     - visibility
#     - ozone
#     - minutely_summary
#     - hourly_summary
#     - daily_summary
#     - precip_intensity_max
#     - temperature_low
#     - temperature_high
#     - apparent_temperature
#     - alerts

# - platform: waze_travel_time
#   name: "Erlend To Home"
#   origin: person.erlend
#   destination: zone.home
#   region: "EU"
#   avoid_subscription_roads: true

# - platform: waze_travel_time
#   name: "Erlend To Work"
#   origin: person.erlend
#   destination: zone.work
#   region: "EU"
#   avoid_subscription_roads: true

# - platform: waze_travel_time
#   name: "Caroline to home"
#   origin: person.caroline
#   destination: zone.home
#   region: "EU"
#   avoid_subscription_roads: true

- platform: entur_public_transport
  stop_ids:
    - NSR:StopPlace:43677
    - NSR:StopPlace:43417

# - platform: authenticated
#   enable_notification: false

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "time_date"
    - "time_utc"

- platform: websocket_api

- platform: tellstick
  only_named:
    - id: 11 #13
      name: Bathroom Tellstick
    - id: 33
      name: Stua
    - id: 101
      name: Gaming Rom
    - id: 104
      name: Ute
    - id: 135
      name: office_temp
#nc core-tellstick 50801

# - platform: systemmonitor
#   resources:
#     - type: memory_use_percent
#     - type: load_15m
#     - type: processor_use
#     - type: last_boot
#     - type: disk_use_percent
#       arg: /
#     - type: load_5m

#     - type: load_1m

- platform: filter
  name: "filtered consumption"
  entity_id: sensor.pulse_power
  filters:
    - filter: throttle
      window_size: 4
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10

- platform: filter
  name: "filtered consumption extra"
  entity_id: sensor.pulse_power
  filters:
    - filter: throttle
      window_size: 10
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 60

    # - filter: time_simple_moving_average
    #   window_size: 00:05
    #   precision: 0

  #do not work when consumption not in logger.
# - platform: statistics
#   entity_id: sensor.pulse_power
#   name: consumptionRounded
#   sampling_size: 30

# - platform: statistics
#   entity_id: sensor.pulse_power
#   name: consumptionRoundedMore
#   sampling_size: 90

# - platform: statistics
#   name: prisstatistics
#   entity_id: sensor.powerprice
#   max_age:
#     hours: 24

# - platform: statistics
#   name: Powerstatistics
#   entity_id: sensor.electricity_price_sivert_thonstads_vei_6b
#   max_age:
#     hours: 24

# - platform: statistics
#   name: stuastatistics
#   entity_id: sensor.stua_temperature
#   max_age:
#     hours: 168

# - platform: statistics
#   name: Monthlyelectric
#   entity_id: sensor.powerstatistics_mean
#   sampling_size: 3000
#   max_age:
#     days: 30

- platform: statistics
  name: BathroomHumidity
  entity_id: sensor.bathroom_humidity
  state_characteristic: change
  sampling_size: 60
  max_age:
    minutes: 30

- platform: statistics
  name: TSLAStatistics
  sampling_size: 200
  state_characteristic: change
  entity_id: sensor.tsla
  max_age:
    days: 7

# - platform: attributes
#   friendly_name: "Trym Sover Last turned on"
#   attribute: last_triggered
#   icon: "mdi:clock"
#   time_format: "%e %B - %H:%M:%S"
#   entities:
#     - automation.trymsoveron

# - platform: scrape
#   name: 'tslascrape'
#   resource: 'https://finance.yahoo.com/quote/TSLA'
#   select: 'span.C\(\$primaryColor\).Fz\(24px\).Fw\(b\)'
#   #select: '#quote-header-info > div.My\(6px\).Pos\(r\).smartphone_Mt\(6px\) > div > p > span.C\(\$primaryColor\).Fz\(24px\).Fw\(b\)'

# - platform: scrape
#   name: 'GME Scrape'
#   resource: 'https://finance.yahoo.com/quote/GME/'
#   select: '#quote-header-info > div.My\(6px\).Pos\(r\).smartphone_Mt\(6px\) > div.D\(ib\).Va\(m\).Maw\(65\%\).Ov\(h\) > div > span.Trsdu\(0\.3s\).Fw\(b\).Fz\(36px\)'
#   unit_of_measurement: USD
#   value_template: "{{ value | float(default=0)}}"

# Legacy template sensors have been migrated to packages:
# - presence.yaml: peoplehome, ebattery
# - alarm.yaml: alarm, unlockedby
# - weather.yaml: bad_weather
# - garmin.yaml: wear_battery, wear_heart_rate, wear_steps
# - trym.yaml: brightnessfortrymlight, trymsleeptime, trymsleeptimeformatted
# - tyra.yaml: tyrasleeptime, tyrasleeptimeformatted
# - lights/lights.yaml: brightnessforlights, brightnessforupstairslights
# - bedroom.yaml: brightnessforbedroomlights
# - media.yaml: tvsource, speakervolume
    # {% if states.input_select.alarm.state == 'Disarm' %}
    #   {% if float(states.sensor.ute_temperature.state) < float(states.input_number.coldthreshold.state) %}
    #     {{ float(states.input_number.hjemmetemp.state) + float(states.input_number.extradegrees.state) }}
    #   {% else %}
    #     {{ float(states.input_number.hjemmetemp.state) + 0 }}
    #   {% endif %}
    # {% elif states.input_select.alarm.state == 'Arm Home'%}
    #     {{ float(states.input_number.nattatemp.state) }}
    # {% else %}
    #   {% if float(states.sensor.ute_temperature.state) < float(states.input_number.coldthreshold.state) %}
    #     {{ float(states.input_number.bortetemp.state) + float(states.input_number.extradegrees.state) }}
    #   {% else %}
    #     {{ [15, (float(states.input_number.bortetemp.state)) - (float(states.sensor.distancefromhome.state)/10) | round(0)] | max }}
    #   {% endif %}
    # {% endif %}
# - platform: mqtt
#   name: "Table light energy"
#   state_topic: "tele/SONOFF-1/ENERGY"
#   value_template: "{{ value_json.Today }}"
#   unit_of_measurement: "kWh"
# - platform: mqtt
#   name: "Table light power"
#   state_topic: "tele/SONOFF-1/ENERGY"
#   value_template: "{{ value_json.Power }}"
#   unit_of_measurement: "W"
# - platform: mqtt
#   name: "Table light voltage"
#   state_topic: "tele/SONOFF-1/ENERGY"
#   value_template: "{{ value_json.Voltage }}"
#   unit_of_measurement: "V"

#Diff
# {%-set targetTemp = temp | float(default=0)%}
# {%-set currentTemp = states.climate.varmepumpe.attributes.current_temperature | float(default=0)%}
# {%-set difference = (currentTemp - targetTemp) | int(default=0) %}
# {%-set temp = temp - difference -%}
# {{temp}}

#Something wrong with quota?

# - platform: google_geocode
#   name: 'Caroline Location'
#   origin: device_tracker.life360_caroline_winge
#   options: street_number, street, city
#   display_zone: hide
#   gravatar: youremail@address.com
#   api_key: !secret maps_api_key

# - platform: google_geocode
#   name: 'Erlend Location'
#   origin: device_tracker.life360_erlend_sellie
#   display_zone: hide
#   gravatar: youremail@address.com
#   api_key: !secret maps_api_key

# - platform: scrape
#   resource: https://www.home-assistant.io
#   select: ".btn-success"
#   username: erlends@onevoice.no
#   password: onkelpinball
