# - platform: ffmpeg_noise
#   input: !secret tyra_tapo_hq
#   extra_arguments: -filter:a highpass=f=400,lowpass=f=2500,volume=volume=2 -codec:a libmp3lame -ar 16000
#   initial_state: off
#   duration: 5
#   reset: 10
#   peak: -20
#   name: Nursery Noise

# - platform: ffmpeg_noise
#   name: "Tyra sound"
#   input: !secret tyra_tapo_hq
#   extra_arguments: -filter:a highpass=f=300,lowpass=f=2500,volume=volume=2 -codec:a libmp3lame -ar 16000
#   output: -f mp3 icecast://stream_user:stream_pw@127.0.0.1:8000/babyphone.mp3
#   initial_state: false
#   duration: 2
#   reset: 60
#   peak: -32

#had some minor error.
# - platform: car_wash
#   weather: weather.home

- platform: command_line
  name: "byasen.duckdns"
  command: curl -m 3 -s byasen.duckdns.org:8123/ > /dev/null && echo ON || echo OFF
  scan_interval: 180

# - platform: ping
#   name: "ipad"
#   host: 192.168.1.6

# - platform: ping
#   name: "XPS"
#   host: 192.168.1.50

# - platform: command_line
#   command: 'curl -X GET -H "Content-type: application/json" -H "kp-api-token: {{states.sensor.postenapikey.state}}"  https://www.posten.no/levering-av-post/_/service/no.posten.website/delivery-days?postalCode=7072'
#   name: MailTodayBinary
# json_attributes:
#   - nextDeliveryDays
# value_template: "{{'i dag' in (value_json | string) }}"
# scan_interval: 57600
# command_timeout: 30

# - platform: bayesian
#   prior: 0.5
#   name: "Home"
#   probability_threshold: 0.9
#   observations:
#     - entity_id: "device_tracker.bt"
#       prob_given_true: 0.75
#       prob_given_false: 0.1
#       platform: "state"
#       to_state: "home"
#     - entity_id: "device_tracker.wifi"
#       prob_given_true: 0.75
#       prob_given_false: 0.1
#       platform: "state"
#       to_state: "home"
#     - entity_id: "device_tracker.life360"
#       prob_given_true: 0.75
#       prob_given_false: 0.1
#       platform: "state"
#       to_state: "home"

# Legacy template binary_sensors have been migrated to packages:
# - presence.yaml: echarging, ccharging, erlend_living_room, anykidshomeandawake, erlendhome, carolinehome
# - media.yaml: tv_on, bed_tv_idle, bedtvon
# - upstairsdoors.yaml: stairsexposed, upstairstairs
# - lights/lights.yaml: drivewaylightshouldbeon
# - iotlinkstasjonar.yaml: motion_office_nexa
# - laundry.yaml: washing, drying
# - tesla.yaml: garage_occupied, tesla_in_garage
# - golf.yaml: golf_in_garage
# - trym.yaml: trym_home
# - tyra.yaml: tyra_home
# - weather.yaml: sun_above_horizon, dark_outside
#((is_state('device_tracker.erlend_wifi','home')
#and is_state('device_tracker.life360_erlend_sellie','home')))}}" #device_tracker.pi_g_watch_r_7594

#(is_state('device_tracker.caroline_wifi','home')
#and is_state('device_tracker.life360_caroline_winge','home'))}}"

# value_template: >
#   {% set threshold = 2 %}
#   {% set weight = namespace(a=0) %}
#   {% for entity_id in states.group.erlend.attributes.entity_id %}
#     {% if states(entity_id) == 'home' %}
#           {% if entity_id == 'device_tracker.life360_erlend_sellie' %}
#               {% set weight.a = weight.a + 1 %}
#           {% endif %}
#           {% if entity_id == 'device_tracker.erlend_wifi' %}
#               {% set weight.a = weight.a + 1 %}
#           {% endif %}
#           {% if entity_id == 'device_tracker.erlend_bt' %}
#               {% set weight.a = weight.a + 2 %}
#           {% endif %}
#       {% endif %}
#   {% endfor %}
#   {%if weight.a >= threshold %}
#     true
#   {%else%}
#     false
#   {%endif%}
