# - platform: ffmpeg_noise
#   input: !secret tyra_tapo_hq
#   extra_arguments: -filter:a highpass=f=400,lowpass=f=2500,volume=volume=2 -codec:a libmp3lame -ar 16000
#   initial_state: off
#   duration: 5
#   reset: 10
#   peak: -20
#   name: Nursery Noise

# - platform: ffmpeg_noise
#   name: "Tyra sound"
#   input: !secret tyra_tapo_hq
#   extra_arguments: -filter:a highpass=f=300,lowpass=f=2500,volume=volume=2 -codec:a libmp3lame -ar 16000
#   output: -f mp3 icecast://stream_user:stream_pw@127.0.0.1:8000/babyphone.mp3
#   initial_state: false
#   duration: 2
#   reset: 60
#   peak: -32

- platform: car_wash
  weather: weather.home

- platform: command_line
  name: "byasen.duckdns"
  command: curl -m 3 -s byasen.duckdns.org:8123/ > /dev/null && echo ON || echo OFF
  scan_interval: 180

- platform: ping
  name: "ipad"
  host: 192.168.1.6

# - platform: ping
#   name: "XPS"
#   host: 192.168.1.50

- platform: command_line
  command: >-
    curl 'https://www.posten.no/levering-av-post-2020/_/component/main/1/leftRegion/1?postCode=7072' \
      -H 'x-requested-with: XMLHttpRequest' \
      --compressed
  name: MailTodayBinary
  # json_attributes:
  #   - nextDeliveryDays
  value_template: "{{'i dag' in (value_json | string) }}"
  scan_interval: 57600
  command_timeout: 30

# - platform: bayesian
#   prior: 0.5
#   name: "Home"
#   probability_threshold: 0.9
#   observations:
#     - entity_id: "device_tracker.bt"
#       prob_given_true: 0.75
#       prob_given_false: 0.1
#       platform: "state"
#       to_state: "home"
#     - entity_id: "device_tracker.wifi"
#       prob_given_true: 0.75
#       prob_given_false: 0.1
#       platform: "state"
#       to_state: "home"
#     - entity_id: "device_tracker.life360"
#       prob_given_true: 0.75
#       prob_given_false: 0.1
#       platform: "state"
#       to_state: "home"

- platform: template
  scan_interval: 10
  sensors:
    mailtoday:
      friendly_name: "Mail Today"
      value_template: "{{states.sensor.mailtoday.state == 'True'}}"
    echarging:
      value_template: "{{states.binary_sensor.oneplus_is_charging.state == 'on'}}"
    ccharging:
      value_template: "{{states.binary_sensor.caroline_charging.state == 'on'}}"
    tv_on:
      value_template: "{{ states.media_player.tv_stua.state == 'Playing'}}"
    garageanddooropen:
      device_class: opening
      value_template: "{{(states.binary_sensor.garage_backdoor.state == 'on' and states.cover.garage_door.state == 'on') and (states.binary_sensor.door_downstair.state == 'on' or states.binary_sensor.veranda.state == 'on') }}"
    stairsexposed:
      device_class: opening
      value_template: >-
        {{(states.binary_sensor.grind.state == 'on' and states.group.innedorsensorer.state == 'on')
        and ((states.input_boolean.trymasleep.state == 'off' and states.binary_sensor.trym_home.state == 'on') 
        or (states.input_boolean.tyraasleep.state == 'off' and states.binary_sensor.tyra_home.state == 'on'))}}
    upstairstairs:
      device_class: opening
      value_template: "{{states.binary_sensor.grind_oppe.state == 'on' and states.binary_sensor.tyra_home.state == 'on' and states.input_boolean.tyraasleep.state == 'on'}}"
    bed_tv_idle:
      friendly_name: "Bed TV Idle"
      value_template: >-
        {{(states.media_player.bedroom.state == 'idle' or 
        states.media_player.bedroom.state == 'paused' or 
        states.media_player.bedroom.state == 'off')
        and states.media_player.tv_soverommet.state == 'on'}}
      delay_on:
        minutes: 5
    bedtvon:
      friendly_name: Bedroom TV is on
      value_template: >-
        {{states.media_player.tv_soverommet.state == 'on'}}
      delay_off:
        minutes: 2
    eprobablyasleep:
      friendly_name: "Erlend Probably Asleep"
      value_template: >-
        {{states.sensor.oneplus_sleep_confidence.state | int(default=0) > 93}}
    garagelightshouldbeon:
      friendly_name: "Garage Light should be on"
      delay_off:
        minutes: 5
      value_template: >-
        {{states.binary_sensor.motion_garage.state == 'on' or states.cover.garage_door.state == 'open'}}
    drivewaylightshouldbeon:
      friendly_name: "Driveway Light should be on"
      delay_off:
        minutes: 5
      value_template: >-
        {{states.sun.sun.attributes.elevation < 0 and (
        states.cover.garage_door.state == 'open' or
        states.binary_sensor.hoveddor.state == 'on' or
        states.binary_sensor.motion_driveway.state == 'on' or
        states.binary_sensor.front_door_motion.state == 'on' or 
        states.binary_sensor.motion_garage.state == 'on')}}

    # value_template: "{{(states.binary_sensor.grind_oppe.state == 'on' and ((states.input_boolean.trymasleep.state == 'on' and states.binary_sensor.trym_home.state == 'on') or states.input_boolean.tyraasleep.state == 'on'))}}"

    # garagestatus:
    #   device_class: opening
    #   value_template: "{{ is_state('switch.garagestatus', 'on') }}"
    # cheaperpower:
    #   friendly_name: "Power is kinda cheap"
    #   value_template: "{{ states('sensor.electricity_price_sivert_thonstads_vei_6b.state')| float(default=0) < states('sensor.electricity_price_sivert_thonstads_vei_6b.attributes.avg_price')| float(default=0) }}"

    motion_driveway_or_garage:
      friendly_name: "Motion Driveway or Garage"
      device_class: motion
      value_template: "{{states.binary_sensor.motion_garage.state == 'on' or states.binary_sensor.motion_driveway.state == 'on'}}"
    motion_office_nexa:
      friendly_name: "Motion Office"
      device_class: motion
      value_template: "{{ is_state('switch.soverombevegelse', 'on') }}"

    washing:
      friendly_name: "Washing"
      device_class: power
      delay_on:
        seconds: 20
      delay_off:
        minutes: 5
      value_template: "{{states.sensor.vaskemaskin_electric_w.state | float(default=0)> 10 }}"
      icon_template: >-
        {% if is_state("binary_sensor.washing", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
      #{{((as_timestamp(states.sensor.vaskemaskin_remaining_program_time.state) or (as_timestamp(utcnow()) + 61)) - as_timestamp(utcnow())) < 60}}
    drying:
      friendly_name: "drying"
      device_class: power
      delay_on:
        seconds: 30
      delay_off:
        minutes: 5
      value_template: "{{states.sensor.torketrommel_electric_w.state | float(default=0)> 300}}"
      icon_template: >-
        {% if is_state("binary_sensor.drying", "on") %}
          mdi:tumble-dryer
        {% else %}
          mdi:tumble-dryer-off
        {% endif %}
    erlend_living_room:
      friendly_name: "Erlend in living room"
      device_class: occupancy
      value_template: "{{ states('sensor.phone_beacon_living')|float(default=-100) > -80 }}"
    garage_occupied:
      friendly_name: "Garage Occupied"
      device_class: occupancy
      delay_off:
        minutes: 2
      delay_on:
        minutes: 2
      value_template: "{{(states.sensor.ultrasonic_sensor.state | float(default=0) < 1.5)}}"
      icon_template: >
        {% if (state == 'off')%}
        mdi:car-off
        {% else %}
        mdi:car
        {% endif %}
    tesla_in_garage:
      friendly_name: "Tesla In Garage"
      device_class: occupancy
      delay_off:
        minutes: 2
      delay_on:
        minutes: 2
      value_template: >-
        {{
        (states.sensor.ultrasonic_sensor.state | float(default=0) < 0.4)
        and (states.sensor.ultrasonic_sensor.state | float(default=0) > 0.1) 
        }}
      icon_template: >
        {% if (state == 'off')%}
        mdi:car-off
        {% else %}
        mdi:car-electric
        {% endif %}
    trym_home:
      device_class: occupancy
      value_template: "{{ is_state('input_boolean.tryminkindergarden', 'off') }}"
    tyra_home:
      device_class: occupancy
      value_template: "{{ is_state('input_boolean.tyrainkindergarden', 'off') }}"
    anykidshomeandawake:
      device_class: occupancy
      value_template: >-
        {{
          (states.input_boolean.tyraasleep.state == 'off' and states.binary_sensor.tyra_home.state == 'on')
            or
          (states.input_boolean.trymasleep.state == 'off' and states.binary_sensor.trym_home.state == 'on')
        }}
    # passathome:
    #   friendly_name: "Passat Home"
    #   device_class: occupancy
    #   value_template: "{{states.binary_sensor.tile_garage.state == 'on' or states.binary_sensor.tile_home.state == 'on' }}"
    #   delay_off:
    #     seconds: 180
    #   icon_template: >
    #     {% if (state == 'off')%}
    #     mdi:car-off
    #     {% else %}
    #     mdi:car
    #     {% endif %}
    erlendhome:
      friendly_name: "Erlend Home"
      device_class: presence
      entity_picture_template: /local/CVbilde.jpg
      # entity_id:
      #   - device_tracker.erlend_bt
      #   - device_tracker.erlend_wifi
      #   - device_tracker.life360_erlend_sellie
      #   - sensor.date_time
      # value_template: "{{is_state('device_tracker.erlend_bt','home') or is_state('person.erlend','home')}}"
      value_template: "{{is_state('person.erlend','home')}}"
    carolinehome:
      friendly_name: "Caroline Home"
      device_class: presence
      entity_picture_template: /local/caroline.png
      # entity_id:
      #   - device_tracker.caroline_bt
      #   - device_tracker.caroline_wifi
      #   - device_tracker.life360_caroline_winge #TODO Caroline and on last or. Fixed because buggy wifi.
      # value_template: "{{is_state('device_tracker.caroline_bt','home') or states.person.caroline.state == 'home' }}"
      value_template: "{{states.person.caroline.state == 'home' }}"
    sun_above_horizon:
      value_template: "{{states('sun.sun') == 'above_horizon'}}"
#((is_state('device_tracker.erlend_wifi','home')
#and is_state('device_tracker.life360_erlend_sellie','home')))}}" #device_tracker.pi_g_watch_r_7594

#(is_state('device_tracker.caroline_wifi','home')
#and is_state('device_tracker.life360_caroline_winge','home'))}}"

# value_template: >
#   {% set threshold = 2 %}
#   {% set weight = namespace(a=0) %}
#   {% for entity_id in states.group.erlend.attributes.entity_id %}
#     {% if states(entity_id) == 'home' %}
#           {% if entity_id == 'device_tracker.life360_erlend_sellie' %}
#               {% set weight.a = weight.a + 1 %}
#           {% endif %}
#           {% if entity_id == 'device_tracker.erlend_wifi' %}
#               {% set weight.a = weight.a + 1 %}
#           {% endif %}
#           {% if entity_id == 'device_tracker.erlend_bt' %}
#               {% set weight.a = weight.a + 2 %}
#           {% endif %}
#       {% endif %}
#   {% endfor %}
#   {%if weight.a >= threshold %}
#     true
#   {%else%}
#     false
#   {%endif%}
