input_boolean:
  pauseclimatecontrol:
    name: Pause Climate Control For Today

automation:
  - id: ResetPauseclimatecontrolfortoday
    alias: ResetPauseclimatecontrolfortoday
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.pauseclimatecontrol
        state: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pauseclimatecontrol

template:
  - binary_sensor:
      - name: "usingspot"
        unique_id: usingspot_sensor
        state: >-
          {{ states('input_boolean.pauseclimatecontrol') == 'off' }}
