blueprint:
  name: PriceAnalyzer - Control Climate
  description: >-
    Control a climate entity with PriceAnalyzer(https://github.com/erlendsellie/priceanalyzer)
    and an input number as a target temperature.
    The climate target temperature will update whenever input number is changed, or PriceAnalyzer updates.
    This Blueprint also requires 'Multiply Correction', which is an input number where you can multiply the correction made by Priceanalyzer by for example 2 or 3.
  domain: automation
  input:
    sensor:
      name: PriceAnalyzer
      description: PriceAnalyzer Sensor
      selector:
        entity:
          integration: priceanalyzer
          domain: sensor
    number:
      name: Base Setpoint Temperature
      description: Input Number Helper for base setpoint temperature
      selector:
        entity:
          domain: input_number
    climate:
      name: Climate
      description: Climate Entity to control
      selector:
        entity:
          domain: climate
    multiply:
      name: Multiply Correction
      description: Input Number Helper To multiply the correction. Useful if you want more aggressive control.
      selector:
        entity:
          domain: input_number
  source_url: https://github.com/erlendsellie/HomeAssistantConfig/blob/master/blueprints/automation/erlendsellie/priceanalyzer_multiply.yaml
mode: restart
max_exceeded: silent
trigger_variables:
  sensor: !input sensor
  number: !input number
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
      - !input sensor
      - !input number
      - !input multiply
action:
  - variables:
      sensor: !input sensor
      number: !input number
      climate: !input climate
      multiply: !input multiply
  - condition: template
    value_template: "{{ states(climate) == 'heat' or states(climate) == 'off'}}"
  - service: climate.set_temperature
    data_template:
      entity_id: !input climate
      temperature: >-
        {%-set baseTemp = states(number) | float(default=0)%}
        {%-set priceanalyzer = states(sensor) | float(default=0)%}
        {% set multiplyNumber = states(multiply) | float(default=1)  %}
        {{baseTemp + (priceanalyzer * multiplyNumber)}}
