blueprint:
  name: PriceAnalyzer - Control Hot Water Tank
  description: >-
    Control a Hot Water climate entity with PriceAnalyzer(https://github.com/erlendsellie/priceanalyzer)
    The Hot Water tank will be controlled based on the Hot water tank target sensor from PriceAnalyzer.
  domain: automation
  input:
    sensor:
      name: PriceAnalyzer
      description: PriceAnalyzer VVB Sensor
      selector:
        entity:
          domain: sensor
    climate:
      name: Hot Water Heater
      description: Your hot water heater climate entity
      selector:
        entity:
          domain: climate
  source_url: https://github.com/erlendsellie/HomeAssistantConfig/blob/master/blueprints/automation/erlendsellie/priceanalyzer_vvb.yaml
mode: restart
max_exceeded: silent
trigger_variables:
  sensor: !input sensor
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: 2
  - platform: state
    entity_id:
      - !input sensor
    for:
      minutes: 2
action:
  - variables:
      sensor: !input sensor
      climate: !input climate
  - condition: template
    value_template: "{{ states(climate) == 'heat' or states(climate) == 'off'}}"
  - service: climate.set_temperature
    data_template:
      entity_id: !input climate
      temperature: >-
        {%-set priceanalyzer = states(sensor) | float(default=0)%}
        {{priceanalyzer}}
