blueprint:
  name: Tibber - Reload Integration
  description:
    Reload Tibber Integration When the API freezes. Will reload 30 seconds
    and 2 minutes after freeze is detected.
  domain: automation
  input:
    entity:
      name: Tibber Entity
      description:
        Entity to base the automation upon. Typically the Tibber Pulse
        Power sensor,  but for if you have solar, the average consuption sensor is
        better to use.
      selector:
        entity:
          integration: tibber
          domain: sensor
          device_class: power
    notify:
      name: Notify
      description:
        Notify with a Persistent Notification in Home Assistant whenever
        Tibber freezes and we reload the integration.
      default: false
      selector:
        boolean:
  source_url: https://github.com/erlendsellie/HomeAssistantConfig/blob/master/blueprints/automation/erlendsellie/tibber_reload.yaml
mode: restart
max_exceeded: silent
trigger_variables:
  entity: !input entity
trigger:
  - platform: state
    entity_id: !input entity
    for:
      seconds: 30
  - platform: state
    entity_id: !input entity
    for:
      minutes: 2
  - platform: template
    value_template: >-
      {%set tibber = states[entity]%}
      {{
        tibber == 'unknown' or
        tibber == 'unavailable'
      }}
    for:
      seconds: 20
action:
  - variables:
      entity: !input entity
      notify: !input notify
  - service: homeassistant.reload_config_entry
    entity_id: !input entity
  - condition: "{{ notify == true }}"
  - delay:
      seconds: 10
  - service: persistent_notification.create
    data:
      title: Tibber var utilgjengelig, relastet integrasjonen
      message: >-
        {% if (as_timestamp(utcnow()) - as_timestamp(states[entity].last_changed)) < 30%}
        Tibber er tilgjengelig igjen -
        {%else%}
        TIBBER ER FREMDELES UTILGJENGELIG -
        {%endif%}
        Sist endret nå for {{relative_time(states[entity].last_changed)}} siden.
