
- alias: ClimateToiletNotWorking
  trigger:
  - platform: template
    value_template: >- 
      {{(states.climate.toilet_heater.attributes.current_temperature - 
      states.climate.toilet_heater.attributes.temperature)
      > 2}}
  action:
  - service: switch.turn_off
    entity_id: switch.toilet_heater


- alias: ClimateToiletNotWorkingNotify
  trigger:
  - platform: template
    value_template: >- 
      {{(states.climate.toilet_heater.attributes.current_temperature - 
        states.input_number.hjemmetemp.state | float)
      > 2}}
    for:
      hours: 2
  action:
  - service: switch.turn_off
    entity_id: switch.toilet_heater
  - service: script.turn_on
    entity_id: script.notify
    data_template:
      variables:
        title: 'Advarsel'
        message: ' Temperaturen på toalettet er {{states.climate.toilet_heater.attributes.current_temperature}}'