
- alias: 'MowingProblem'
  trigger:
  - platform: state
    entity_id: binary_sensor.robot_problem
    to: 'on'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.robot_problem
    to: 'on'
    for:
      minutes: 20
  - platform: state
    entity_id: binary_sensor.robot_mowing
    to: 'off'
    for:
      minutes: 60
  - platform: state
    entity_id: binary_sensor.robot_charging
    to: 'off'
    for:
      minutes: 220
  condition:
    condition: and
    conditions:
    - condition: time
      after: '08:10:00'
      before: '19:00:00'    
    - condition: state
      entity_id: binary_sensor.robot_should_stop
      state: 'off'
  action:
  - service: notify.me
    data_template:
      message: 'Gressklipper sitter fast!'
  - service: script.turn_on
    entity_id: script.say
    data_template:
      variables:
        message: 'Gressklipperen sitter fast.'


- alias: 'StopMowing'
  trigger:
  - platform: state
    entity_id: binary_sensor.robot_should_stop
    to: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.mower


- alias: 'StartMowing'
  trigger:
  - platform: state
    entity_id: binary_sensor.robot_should_stop
    to: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.mower





# - alias: 'MowerDidNotFinish'
#   trigger:
#   - platform: time
#     at: "10:00:00"
#   - platform: time
#     at: "20:00:00"
#   # - platform: state
#   #   entity_id: binary_sensor.robot_charging
#   #   to: 'off'
#   #   for:
#   #     minutes: 220
#   condition:
#   - condition: state
#     entity_id: binary_sensor.robot_charging
#     state: 'off'
#   action:
#   - service: script.turn_on
#     entity_id: script.notifyhome
#     data_template:
#       variables:
#         message: 'Gressklipperen kom seg ikke hjem, redd den.'
#   - service: script.turn_on
#     entity_id: script.say
#     data_template:
#       variables:
#         message: 'Gressklipperen lader ikke.'
#   - wait_for_trigger:
#     - platform: state
#       entity_id: switch.mower
#       to: "off"
#       for:
#         seconds: 15
#     timeout: 60
#     continue_on_timeout: false          
#   - service: switch.turn_on
#     entity_id: switch.mower