automation:
  - id: reloadPowerStuff
    alias: reloadPowerStuff
    trigger:
      # - platform: time
      #   at: "18:00:00"
      # - platform: time
      #   at: "00:02:00"
    action:
      - service: homeassistant.reload_config_entry
        entity_id: sensor.priceanalyzer
      - service: homeassistant.reload_config_entry
        entity_id: sensor.nordpool
      # - service: homeassistant.reload_config_entry
      #   entity_id: sensor.priceanalyzer_se2
      # - service: homeassistant.reload_config_entry
      #   entity_id: sensor.priceanalyzer_kr_sand
      # - service: homeassistant.reload_config_entry
      #   entity_id: sensor.priceanalyzer_no4
      # - service: homeassistant.reload_config_entry
      #   entity_id: sensor.priceanalyzer_oslo

  - id: tomorrow_valid_wrong
    alias: tomorrow_valid_wrong
    trigger:
      - platform: time
        at: "12:00:00"
    condition:
      - condition: state
        entity_id: binary_sensor.priceanalyzer_tomorrow_valid
        state: "on"
    action:
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Tomorrow_valid is wrong for Priceanalyzer!
            message: >-
              Nordpool tomorrow valid is {{states('binary_sensor.nordpool_tomorrow_valid')}}.
              What about raw_tomorrow?

#value_template: >-
# {%set hour = now().hour%}
# {%if hour > 21 or hour < 6%}
#   {{ 0.01 }}
# {%else%}
#   {{0.0787 + 0.01 }}
# {% endif %}

#{"default_temp": 75, "five_most_expensive": 40, "is_falling": 50, "five_cheapest": 65, "ten_cheapest": 60, "low_price": 50, "not_cheap_not_expensive": 50, "min_price_for_day": 80}
#{"default_temp": 75, "five_most_expensive": 40, "is_falling": 50, "five_cheapest": 70, "ten_cheapest": 60, "low_price": 50, "not_cheap_not_expensive": 50, "min_price_for_day": 80}
