#LesMeg:
# Fjern alle kall til script.notify, eller bytt om til egen notify service call,
# om du vil ha varsling med status.
template:
  - binary_sensor:
      # Sensor som trigger automasjon om Tibber fryser.
      # Denne sensoren blir true, når det er over 2 minutter siden Pulse-sensoren har oppdatert seg, ca.
      # OBS! Har du solceller på taket, kan Tibber Pulse-sensoren din være 0, uten at sensoren er fryst.
      # bruk da en annen sensor, for eksempel 'kostnad i dag' eller 'gjennomsnitt i dag', som rapporterer data ofte fra Tibber.
      - name: "Tibber Unavailable"
        delay_on:
          seconds: 20
        state: >-
          {{
            as_timestamp(now())
            - 
            as_timestamp(states.sensor.power_sivert_thonstads_vei_6b.last_changed)
            | float
            > 10
          }}

#TODO Fiks varsling for å varsle riktig når sensor blir tilgjengelig igjen,
# om den feiler ved første relasting.
automation:
  - id: reloadTibber
    alias: reloadTibber
    trigger:
      - platform: state
        entity_id: binary_sensor.tibber_unavailable
        to: "on"
    action:
      - repeat:
          while: "{{is_state('binary_sensor.tibber_unavailable','on') and repeat.index < 5 }}" #Do it 4 times.
          sequence:
            - service: homeassistant.reload_config_entry
              entity_id: sensor.power_sivert_thonstads_vei_6b
            - delay:
                seconds: 10
            #Varsling med sensor-verdi, 10 sekunder etter relasting av integrasjonen.
            - condition: "{{is_state('binary_sensor.tibber_unavailable','on')  and repeat.index < 4}}"
            - service: script.notify
              data:
                title: Tibber var utilgjengelig, relastet integrasjonen.
                message: >-
                  Tibber er fortsatt utilgjengelig, prøver på nytt om {{1 * repeat.index}} minutter.
                  Sist endret for {{relative_time(states.sensor.power_sivert_thonstads_vei_6b.last_changed)}} siden
            - condition: "{{is_state('binary_sensor.tibber_unavailable','on')  and repeat.index < 4}}"
            - delay:
                minutes: "{{ repeat.index }}"
      #Varsling med sensor-verdi etter loop.
      - service: script.notify
        data:
          title: Tibber var utilgjengelig, relastet integrasjonen
          message: >-
            {%if is_state('binary_sensor.tibber_unavailable','on')%}
            Tibber er fortsatt utilgjengelig, gir opp etter 3 forsøk.
            {%else%}
            Tibber er tilgjengelig,
            {%endif%}
            Sist endret for {{relative_time(states.sensor.power_sivert_thonstads_vei_6b.last_changed)}} siden
