#simplified package, should work more out of the box.
automation:
  - id: reloadTibberSimple
    alias: reloadTibberSimple
    trigger:
      - platform: state
        entity_id: sensor.pulse_power
        for:
          seconds: 30
      - platform: state
        entity_id: sensor.pulse_power
        for:
          minutes: 2
    action:
      - service: homeassistant.reload_config_entry
        entity_id: sensor.pulse_power
      - service: persistent_notification.create
        data:
          title: Tibber var utilgjengelig, relastet integrasjonen
          message: >-
            Sist endret for {{relative_time(states.sensor.pulse_power.last_changed)}} siden
