template:
  - binary_sensor:
      #     - name: "vvb_on"
      #       # delay_on:
      #       #   minutes: 3
      #       delay_off:
      #         seconds: 10
      #       state: >-
      #         {%-set notUsingSpot = states.binary_sensor.usingspot.state == 'off' -%}
      #         {%-set pause = states.input_boolean.vvb_on.state == 'on' -%}
      #         {%-set isLowPrice = states.binary_sensor.islowprice.state == 'on' -%}
      #         {%-set shouldNotBother = states.binary_sensor.pricedifferenceissmall.state == 'on' -%}
      #         {%set pricelevel = states('sensor.pricelevel')%}
      #         {%set pricecorrectionDown = states('sensor.pricecorrection') | int  < 0%}
      #         {%set isCheap = pricelevel ==  'CHEAP' or pricelevel == 'VERY_CHEAP'%}
      #         {%set current_hour = states.sensor.priceanalyzer.attributes.current_hour%}
      #         {%set is_ten_cheapest = current_hour.is_ten_cheapest %}
      #         {% if pause%}
      #           {{true}}
      #         {% elif shouldNotBother %}
      #           {{true}}
      #         {% elif notUsingSpot%}
      #           {{true}}
      #         {% elif is_ten_cheapest%}
      #           {{true}}
      #         {% else %}
      #           {{isLowPrice or isCheap}}
      #         {% endif %}
      - name: "Using Hot Water"
        delay_off:
          seconds: 10
        state: >-
          {{
            states.sensor.vvb_difference_statistics.state | float(default=0) < -0.5
          }}

  - sensor:
      - name: "vvb_temp"
        unit_of_measurement: "°C"
        state: >-
          {%-set notUsingSpot = states.binary_sensor.usingspot.state == 'off' -%}
          {%-set turn_on = states.input_boolean.vvb_on.state == 'on' -%}
          {%-set turn_off = states.input_boolean.vvb_off.state == 'on' -%}
          {%-set limit = states.input_boolean.limit_water_heater.state == 'on' -%}
          {%-set isLowPrice = states.binary_sensor.islowprice.state == 'on' -%}
          {%-set shouldNotBother = states.binary_sensor.pricedifferenceissmall.state == 'on' -%}
          {%set pricelevel = states('sensor.pricelevel')%}
          {%set pricecorrectionDown = states('sensor.pricecorrection') | int  < 0%}
          {%set isCheap = pricelevel ==  'CHEAP' or pricelevel == 'VERY_CHEAP'%}
          {%set current_hour = states.sensor.priceanalyzer.attributes.current_hour%}
          {%set is_ten_cheapest = current_hour.is_ten_cheapest %}
          {%set current_temp = states.climate.varmtvannsbereder.attributes.current_temperature  | float(default=50)%}
          {%set temp = 60%}
          {% if limit or turn_off%}
            {%set temp = 20%}
          {% elif notUsingSpot or turn_on%}
            {%set temp = 80%}
          {%else%}
            {%set temp = states.sensor.vvbsensor.state %}
          {% endif %}
          {{temp}}
      - name: "VVB Average"
        unit_of_measurement: "°C"
        state: >-
          {%set bottom = states('sensor.vvb_bottom') | float(default=50)%}
          {%set top = states('sensor.vvb_top') | float(default=50)%}
          {{average(top,bottom)}}
      - name: "VVB Average2"
        unit_of_measurement: "°C"
        state: >-
          {%set bottom = states('sensor.vvb_bottom') | float(default=50)%}
          {%set avg = states('sensor.vvb_average') | float(default=50)%}
          {{average(bottom,avg)}}
      - name: "VVB Min"
        unit_of_measurement: "°C"
        state: >-
          {%set bottom = states('sensor.vvb_bottom') | float(default=50)%}
          {%set top = states('sensor.vvb_top') | float(default=50)%}
          {{min(top,bottom)}}
      - name: "VVB Max"
        unit_of_measurement: "°C"
        state: >-
          {%set bottom = states('sensor.vvb_bottom') | float(default=50)%}
          {%set top = states('sensor.vvb_top') | float(default=50)%}
          {{max(top,bottom)}}
      - name: "VVB Calculated"
        unit_of_measurement: "°C"
        #Todo add so that both top and bottom must be at setpoint?
        state: >-
          {%set average = states('sensor.vvb_average') | float(default=50)%}
          {%set bottom = states('sensor.vvb_bottom') | float(default=50)%}
          {%set top = states('sensor.vvb_top') | float(default=50)%}
          {%set max_temp = max(average,bottom)%}
          {%set temp = max_temp%}
          {{temp}}
      - name: "VVB Difference"
        unit_of_measurement: "°C"
        state: >-
          {%set bottom = states.sensor.vvb_bottom.state | float(default=50)%}
          {%set top = states.sensor.vvb_top.state | float(default=50)%}
          {{bottom - top}}

#Set to on always at some hours at night, to ensure hot water at morning?
# or when car charges = start heater?

sensor:
  - platform: history_stats
    name: VVB today
    entity_id: switch.varmtvannsbereder
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: statistics
    name: VVB Top Statistics
    state_characteristic: change
    entity_id: sensor.vvb_top
    sampling_size: 100
    max_age:
      days: 7

  - platform: statistics
    name: VVB bottom Statistics
    state_characteristic: change
    entity_id: sensor.vvb_bottom
    sampling_size: 100
    max_age:
      days: 7

  - platform: statistics
    name: VVB difference Statistics
    entity_id: sensor.vvb_bottom
    state_characteristic: change
    max_age:
      minutes: 3
    sampling_size: 150
    precision: 1

  - platform: statistics
    name: VVB variance top Statistics
    entity_id: sensor.vvb_top
    state_characteristic: variance
    sampling_size: 100
    max_age:
      minutes: 15
    precision: 1

  - platform: statistics
    name: VVB standard_deviation top Statistics
    entity_id: sensor.vvb_top
    state_characteristic: standard_deviation
    sampling_size: 100
    max_age:
      minutes: 15
    precision: 1

input_boolean:
  vvb_on:
    name: VVB on for rest of today
  vvb_off:
    name: VVB off for rest of today
  vvb_keep_state:
    name: Keep VVB State

automation:
  - id: ResetPauseVVBcontrolfortoday
    alias: ResetPauseVVBcontrolfortoday
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.vvb_keep_state
        state: "off"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id:
            - input_boolean.vvb_on
            - input_boolean.vvb_off

  - id: NotifyVVBKeepStateOn
    alias: NotifyVVBKeepStateOn
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.vvb_keep_state
        state: "on"
    action:
      - service: notify.me
        data:
          message: >-
            Keep VVB State is Turned on. 
            {%if states('input_boolean.vvb_off') == 'on'%}
            Will keep VVB off
            {%endif%}
            {%if states('input_boolean.vvb_on') == 'on'%}
            Will keep VVB on
            {%endif%}

  - id: VVBToggle
    alias: VVBToggle
    trigger:
      - platform: state
        entity_id: sensor.vvb_temp
        # To avoid bugs during restarts, or other, trigger every hour, to avoid cold showers.
      - platform: time_pattern
        minutes: 5 #Every hour, 5 minutes over.
      # - platform: homeassistant
      #   # Event can also be 'shutdown'
      #   event: start
    action:
      - service: climate.set_temperature
        data:
          temperature: "{{states('sensor.vvb_temp') | int(default=70)}}"
        target:
          entity_id: climate.varmtvannsbereder
      - alias: "TurnOn VVB"
        service: >-
          climate.turn_on
        target:
          entity_id: climate.varmtvannsbereder

  - id: NotifyLowVVBTemperature
    alias: "Notify low VVB temperature"
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.vvb_calculated
        below: 40
        for:
          hours: 3
      - platform: template
        value_template: >-
          {{ states('sensor.vvb_calculated') | float(0) < states('sensor.vvb_temp') | float(0) }}
        for:
          hours: 3
    condition:
      - condition: state
        entity_id: input_boolean.keep_vvb_off
        state: "off"
      - condition: template
        value_template: >-
          {{
            is_state('switch.varmtvannsbereder', 'off')
            and (as_timestamp(now()) - as_timestamp(states.switch.varmtvannsbereder.last_changed)) > 12 * 3600
          }}
    action:
      - service: notify.me
        data:
          message: >-
            VVB temperature warning:
            - VVB Calculated: {{ states('sensor.vvb_calculated') }} °C
            - VVB target (vvb_temp): {{ states('sensor.vvb_temp') }} °C
            - VVB switch state: {{ states('switch.varmtvannsbereder') }}

  - id: NotifyVVBSwitchOffTooLong
    alias: "Notify VVB switch off too long"
    mode: single
    trigger:
      - platform: state
        entity_id: switch.varmtvannsbereder
        to: "off"
        for:
          hours: 12
    condition:
      - condition: state
        entity_id: input_boolean.keep_vvb_off
        state: "off"
    action:
      - service: notify.me
        data:
          message: >-
            VVB has been OFF for more than 12 hours while keep_vvb_off is not enabled.
            - VVB Calculated: {{ states('sensor.vvb_calculated') }} °C
            - VVB target (vvb_temp): {{ states('sensor.vvb_temp') }} °C
            - VVB switch state: {{ states('switch.varmtvannsbereder') }}

  # - id: ToggleHeavyDutyToFixPowerReading
  #   alias: ToggleHeavyDutyToFixPowerReading
  #   trigger:
  #     - platform: time_pattern
  #       minutes: "/15"
  #   condition:
  #     - condition: state
  #       entity_id: switch.varmtvannsbereder
  #       state: "on"
  #   action:
  #     - service: switch.turn_off
  #       entity_id: switch.varmtvannsbereder
  #     - delay:
  #         seconds: 3
  #     - service: switch.turn_on
  #       entity_id: switch.varmtvannsbereder

climate:
  - platform: generic_thermostat
    name: Varmtvannsbereder
    heater: switch.varmtvannsbereder
    target_sensor: sensor.vvb_calculated
    min_temp: 20
    max_temp: 80
    precision: 1
    hot_tolerance: 1
    cold_tolerance: 1
    min_cycle_duration:
      minutes: 10
