template:
  - binary_sensor:
      - name: "Should Bathroom Lights Be On"
        unique_id: 4afd0a31-efb0-49e0-9da8-2ae58c0a8394
        delay_off:
          minutes: 20
        attributes:
          motion_bathroom: "{{states.binary_sensor.motion_bathroom.state == 'on'}}"
        state: >-
          {{
            states.binary_sensor.motion_bathroom.state == 'on'
          }}
  - sensor:
      - name: "brightnessforbathroomlights"
        unit_of_measurement: "%"
        state: >-
          {% if states.input_select.alarm.state == 'Arm Home' %} 
          20
          {% elif now().hour >= 21 or now().hour < 6 %}
          50
          {% else %}
          100
          {% endif %}

automation:
  - id: toggleBathroomLights
    alias: toggleBathroomLights
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.should_bathroom_lights_be_on
        to: "on"
      - platform: state
        entity_id: binary_sensor.door_bathroom
        to: "on"
    condition:
      - condition: state
        entity_id: light.bathroom
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.bathroom
        data_template:
          brightness_pct: "{{ states.sensor.brightnessforbathroomlights.state }}"

  - id: turnOffBathroomLights
    alias: turnOffBathroomLights
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.should_bathroom_lights_be_on
        to: "off"
    action:
      - service: light.turn_off
        entity_id: light.bathroom
