automation:
  - alias: Trym Temp High at Noon
    id: trymtemphigh
    trigger:
      - platform: state
        entity_id: binary_sensor.trymtemphigh
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.notifyhome
        data_template:
          variables:
            title: Temperaturen til Trym er {{states.sensor.trym_temp.state}}
            message: Vurder å åpne vinduet for å lufte litt
      - service: script.turn_on
        entity_id: script.say
        data_template:
          variables:
            message: "Temperaturen til Trym er {{states.sensor.trym_temp.state}}"

  - alias: Tyra Temp High at Noon
    id: tyratemphigh
    trigger:
      - platform: state
        entity_id: binary_sensor.tyratemphigh
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.notifyhome
        data_template:
          variables:
            title: "Temperaturen til Tyra er {{states.sensor.tyra_temp.state}}"
            message: Vurder å åpne vinduet for å lufte litt
      - service: script.turn_on
        entity_id: script.say
        data_template:
          variables:
            message: "Temperaturen til Tyra er {{states.sensor.tyra_temp.state}}"

  - alias: Bedroom Temp High at Noon
    id: bedroomtemphigh
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroomtemphigh
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.notifyhome
        data_template:
          variables:
            title: "Temperaturen på Soverommet er {{states.sensor.temp_bedroom.state}}"
            message: Vurder å åpne vinduet for å lufte litt
      - service: script.turn_on
        entity_id: script.say
        data_template:
          variables:
            message: "Temperaturen på Soverommet er {{states.sensor.temp_bedroom.state}}"

template:
  - binary_sensor:
      - name: "trymtemphigh"
        unique_id: trymtemphigh_sensor
        state: >-
          {%-set hour = now().hour | float(default=0)-%}
          {%-set home = states.input_select.alarm.state == 'Disarm'%}
          {%-set windowclosed = states.binary_sensor.trym_window.state == 'off'%}
          {%-set trymtemp = states.sensor.trym_temp.state | float(default=0)%}
          {%-set trymawake = states.input_boolean.trymasleep.state == 'off' %}
          {{trymawake and home and windowclosed and (hour > 17) and (trymtemp > 24)}}

      - name: "tyratemphigh"
        unique_id: tyratemphigh_sensor
        state: >-
          {%-set hour = now().hour | float(default=0)-%}
          {%-set home = states.input_select.alarm.state == 'Disarm'%}
          {%-set windowclosed = states.binary_sensor.tyra_window.state == 'off'%}
          {%-set tyratemp = states.sensor.tyra_temp.state | float(default=0)%}
          {%-set tyraawake = states.input_boolean.tyraawake.state == 'off' %}
          {{tyraawake and home and windowclosed and (hour > 17) and (tyratemp > 24)}}

      - name: "bedroomtemphigh"
        unique_id: bedroomtemphigh_sensor
        delay_off:
          minutes: 120
        state: >-
          {%-set hour = now().hour | float(default=0)-%}
          {%-set home = states.input_select.alarm.state == 'Disarm'%}
          {%-set windowclosed = states.binary_sensor.bedroom_window.state == 'off'%}
          {%-set temp = states.sensor.temp_bedroom.state | float(default=0)%}
          {{home and windowclosed and (hour > 19) and (temp > 25)}}
