automation:
  - alias: GameTimerCheckTemp
    trigger:
      - platform: time_pattern
        minutes: 5 #Every hour, 5 minutes over.
    condition:
      - condition: state
        entity_id: input_boolean.gametimer
        state: "on"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.gametimer1
          value: "{{ states.input_number.gametimer1.state | int(default=0) + states.sensor.gametemp.state | int(default=0) }}"
    # - service: input_number.set_value
    #   data_template:
    #     entity_id: input_number.gametimer2
    #     value: '{{ states.input_number.gametimer2.state | int(default=0) + states.sensor.ute_temperature.state | int(default=0) }}'

  - alias: GameTimerNotify1
    trigger:
      - platform: state
        entity_id: input_number.gametimer1
    condition:
      - condition: numeric_state
        entity_id: input_number.gametimer1
        above: 960
    action:
      - service: notify.me
        data_template:
          message: "Mørningstimer er ferdig! Nåværende døgngrader er {{((states.input_number.gametimer1.state | int(default=0) / 24)) | round(1)}}"

  - alias: GarageCold
    trigger:
      - platform: numeric_state
        entity_id: sensor.gametemp
        below: 0
    condition:
      - condition: state
        entity_id: input_boolean.gametimer
        state: "on"
    action:
      - service: notify.me
        data_template:
          message: "Mørningstemperaturen er under null grader, mens vilt henger til mørning. Temp nå: {{states.sensor.gametemp.state}}"

script:
  resetgametimer1:
    sequence:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.gametimer1
          value: 0
      - service: input_boolean.turn_on
        entity_id: input_boolean.gametimer

input_number:
  gametimer1:
    name: Mørningstimer 1
    min: -0
    max: 3000
    step: 0.1
    mode: box
    unit_of_measurement: "°C"

  gametemp_temp:
    name: Manuell Mørnings Temperatur
    min: 0
    max: 30
    step: 1
    mode: slider
    unit_of_measurement: "C"

  # gametimer2:
  #   name: Mørningstimer 2
  #   min: -0
  #   max: 1500
  #   step: 0.1
  #   mode: box
  #   unit_of_measurement: '°C'

input_boolean:
  gametimer:
    name: "Mørningstimer"

template:
  - sensor:
      - name: "dogngrader1"
        unique_id: dogngrader1_sensor
        unit_of_measurement: "Døgngrader"
        state: >
          {{((states.input_number.gametimer1.state | int(default=0) / 24)) | round(1)}}

      - name: "gametemp"
        unique_id: gametemp_sensor
        unit_of_measurement: "C"
        state: >
          {% set valgt = states('input_select.gametemp') %}
          {% set temp_dict = {
              "Sleipner Utside": states('sensor.modely_temperature_sensor_outside'),
              "Sleipner Innside": states('sensor.modely_temperature_sensor_inside'),
              "Ute": states('sensor.ute_temperature'),
              "Viltnett": states('sensor.viltnett_temperature'),
              "Jaktbod": states('sensor.jaktbod_temp_temperature'),
              "Min Posisjon": states('sensor.erlend_current_temperatur'),
              "Manuell": states('input_number.gametemp_temp')
          } %}
          {% set temp = temp_dict[valgt] %}
          {% set temp_float = temp | float(default=states('input_number.gametemp_temp') | float(10)) %}
          {{ temp_float }}

  - binary_sensor:
      - name: "huntingseason"
        unique_id: huntingseason_sensor
        state: >
          {{states.sensor.date_time.state.split('-')[1] | int(default=0) > 7 or states.sensor.date_time.state.split('-')[1] | int(default=0) < 3}}

input_select:
  gametemp:
    name: "Mørningssted:"
    options:
      - Viltnett
      - Jaktbod
      - Sleipner Utside
      - Sleipner Innside
      - Ute
      - Min Posisjon
      - Manuell
