binary_sensor:
  - platform: template
    scan_interval: 10
    sensors:
      garageanddooropen:
        device_class: opening
        value_template: "{{(states.binary_sensor.garage_backdoor.state == 'on' and states.cover.garage_door.state == 'on') and (states.binary_sensor.door_downstair.state == 'on' or states.binary_sensor.veranda.state == 'on') }}"
      garagelightshouldbeon:
        friendly_name: "Garage Light should be on"
        delay_off:
          minutes: 5
        value_template: >-
          {{states.binary_sensor.motion_garage.state == 'on' or states.cover.garage_door.state == 'open'}}

automation:
  - alias: CloseGarageAfter15minutes
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_driveway_or_garage
        to: "off"
        for:
          minutes: 7
    condition:
      - condition: template
        value_template: "{{ states.cover.garage_door.state  == 'open'}}" #Maybe add garage not occupied?
    action:
      # - service: notify.mobile_app_oneplus
      #   data_template:
      #     title: Garage closed since since movement not detected.
      #     message: Garage closed since since movement not detected.
      #     data:
      #       image: 'https://hjem.sellie.no{{states.camera.driveway.attributes.entity_picture}}'
      - service: cover.close_cover
        entity_id: cover.garage_door
    # - service: notify.mobile_app_oneplus
    #   data_template:
    #     title: 'Garage left open?'
    #     message: 'Close it?'
    #     data:
    #       actions:
    #         - action: closegarage
    #           title: Close it
    #           destructive: true
    #         - action: garageRemind
    #           title: Remind me in 5 minutes
    #           destructive: true

  - alias: Close Garage When someone leaves
    id: CloseGarageWhensomeoneleaves
    trigger:
      - platform: state
        entity_id: binary_sensor.erlendhome
        to: "off"
      - platform: state
        entity_id: binary_sensor.carolinehome
        to: "off"
        #Also do this when garage has been open for some time? Should be safe, as motion is not detected anymore.
    condition:
      - condition: state
        entity_id: cover.garage_door
        state: "open"
    action:
      #When motion in driveway has been off for 1 minutes. Lets wait 15 minutes as a timeout.
      - wait_template: >-
          {{ (states.binary_sensor.motion_driveway.state == 'off')
          and 
          ((as_timestamp(utcnow()) - as_timestamp(states.binary_sensor.motion_driveway.last_changed)) / 60) | round(0) > 1}}
        timeout: "0:15:00"
        #And if timed out, abort with the same logic
      - condition: template
        value_template: >-
          {{ (states.binary_sensor.motion_driveway.state == 'off')
          and 
          ((as_timestamp(utcnow()) - as_timestamp(states.binary_sensor.motion_driveway.last_changed)) / 60) | round(0) > 1}}
      # - service: notify.mobile_app_oneplus
      #   data_template:
      #     title: Garage closed since someone left.
      #     message: Garage closed since someone left.
      #     data:
      #       image: 'https://hjem.sellie.no{{states.camera.driveway.attributes.entity_picture}}'
      - service: cover.close_cover
        entity_id: cover.garage_door

  - alias: Open Garage and unlock when home
    trigger:
      - platform: state
        entity_id: binary_sensor.erlendhome
        to: "on"
        from: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.garage_occupied
        state: "off"
      - condition: state
        entity_id: cover.garage_door
        state: "closed"
    action:
      - service: cover.open_cover
        entity_id: cover.garage_door
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Garage opened because Erlend came home.
            message: Garage opened because Erlend came home.

  - alias: Open Garage and unlock when Caroline home
    trigger:
      - platform: state
        entity_id: binary_sensor.carolinehome
        to: "on"
        from: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.garage_occupied
        state: "off"
      - condition: state
        entity_id: cover.garage_door
        state: "closed"
    action:
      - service: cover.open_cover
        entity_id: cover.garage_door
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Garage opened because Caroline came home.
            message: Garage opened because Caroline came home.

  - alias: Open Garage and unlock when Caroline home from Work
    id: Open Garage and unlock when Caroline home from Work
    trigger:
      platform: zone
      entity_id: person.caroline
      zone: zone.sykehuset
      # Event is either enter or leave
      event: leave
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.carolinehome
            to: "on"
            from: "off"
        timeout: "00:45:00"
        continue_on_timeout: false
      - service: cover.open_cover
        entity_id: cover.garage_door
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Garage opened because Caroline came home from Work.
            message: Garage opened because Caroline came home Work.

  - id: closegarageAlarmAway
    alias: closegarageAlarmAway
    trigger:
      platform: state
      entity_id: input_select.alarm
      to: "Arm Away"
      for:
        seconds: 10
    condition:
      condition: state
      entity_id: cover.garage_door
      state: "open"
    action:
      - service: cover.close_cover
        entity_id: cover.garage_door
    # - service: script.turn_on
    #   entity_id: script.notify
    #   data_template:
    #     variables:
    #       title: Garage closed because Armed away.
    #       message: Garage closed because Armed away.

  - id: Turnalarmhome3
    alias: Turn Alarm home After 3
    trigger:
      - entity_id: input_select.alarm
        platform: state
        to: "Arm Home"
        for:
          minutes: 3
    condition:
      condition: state
      entity_id: cover.garage_door
      state: "open"
    action:
      - service: cover.close_cover
        entity_id: cover.garage_door
    # - service: script.turn_on
    #   entity_id: script.notify
    #   data_template:
    #     variables:
    #       title: Garage closed since it was open when Armed Home.
    #       message: Garage closed since it was open when Armed Home.
