template:
  - binary_sensor:
      - name: Forgot To Lock Golf
        unique_id: forgot_to_lock_golf
        delay_on:
          minutes: 20
        state: >-
          {{
            states.binary_sensor.e_golf_vehicle_moving.state == 'off' and
            states.binary_sensor.e_golf_doors_locked.state == 'on'
          }}
      - name: ShouldKeepChargingGolf
        unique_id: ShouldKeepChargingGolf
        state: >-
          {%set limit = states.input_number.golf_soc_limit.state | float(default=90)%}
          {%set soc = states.sensor.e_golf_battery_level.state | float(default=10)%}
          {%set charging = (states.binary_sensor.e_golf_charging_cable_connected.state == 'on' and states.device_tracker.e_golf_position.state == 'home') %}
          {%set tesla_charging = states.binary_sensor.modely_charger_sensor.state == 'on'%}
          {%set is_heating = states.switch.e_golf_auxiliary_climatisation.state == 'on' or states.switch.e_golf_window_heater == 'on'%}
          {%if(is_heating == true and charging == true) %}
            {{True}}
          {% elif(tesla_charging == true) %}
            {{True}} 
          {% elif(charging == false) %}
            {{True}} 
          {% else %}
            {{soc <= limit}}
          {% endif %}
      - name: Caroline Connected To Golf
        unique_id: CarolineConnectedToGolf
        state: >-
          {% set c = state_attr('sensor.caroline_bluetooth_connection', 
          'connected_paired_devices') %}
          {{ c is not none and c is search('B8:9F:09:F9:F4:B0') }}

      - name: "golf_in_garage"
        unique_id: golf_in_garage_sensor
        device_class: occupancy
        delay_off:
          minutes: 2
        delay_on:
          seconds: 15
        state: >-
          {{
          (states.sensor.ultrasonic_sensor.state | float(default=0) < 0.65)
          and (states.sensor.ultrasonic_sensor.state | float(default=0) > 0.55) 
          }}
        icon: >
          {% if is_state('binary_sensor.golf_in_garage', 'off') %}
          mdi:car-off
          {% else %}
          mdi:car-electric
          {% endif %}

  - sensor:
      - name: "Golf Percent To Charge"
        unit_of_measurement: "%"
        state: >-
          {%set soc = states('sensor.e_golf_battery_level') | int %}
          {{90 - soc | float(default=0)}}
      - name: "Golf kWh To Charge"
        unit_of_measurement: "kWh"
        state: >-
          {{30 * ((states('sensor.golf_percent_to_charge') | float)/100) | round(3)}}
      - name: "Car to charge"
        state: >-
          {%set tesla = states('sensor.modely_kwh_to_charge') | float(default=0)%}
          {%set tesla_soc = states('sensor.modely') | float(default=60)%}
          {%set golf_soc = states('sensor.e_golf_battery_level') | float%}
          {%set golf = states('sensor.golf_kwh_to_charge') | float%}
          {%if golf_soc < 40 and tesla_soc < 40%}
          Both
          {%elif golf_soc < 40%}
          Golf
          {%elif tesla_soc < 40%}
          Tesla
          {%elif tesla > golf%}
          Tesla
          {%else%}
          Golf
          {%endif%}
      - name: "Car Charging"
        state: >-
          {% set tesla_soc = states('sensor.modely') | float(0) %}
          {% set golf_soc = states('sensor.e_golf_battery_level') | float(0) %}
          {% set car_to_charge = states('sensor.car_to_charge') %}
          {% set tesla_charging = is_state('binary_sensor.modely_charger_sensor', 'on') %}
          {% set golf_charging = is_state('binary_sensor.e_golf_charging_cable_connected', 'on') %}

          {% if tesla_charging and car_to_charge == 'Tesla' %}
            Correct car is charging (Tesla)
          {% elif golf_charging and car_to_charge == 'Golf' %}
            Correct car is charging (Golf)
          {% elif tesla_charging %}
            Incorrect car is charging (Tesla)
          {% elif golf_charging %}
            Incorrect car is charging (Golf)
          {% else %}
            No car is charging
          {% endif %}
          You should charge {{ car_to_charge }} tonight. Tesla: {{ tesla_soc }}%, Golf: {{ golf_soc }}%

  #     - name: ErHjemmeUke
  #       unique_id: ErHjemmeUke
  #       state: >-
  #         {%set week_number = now().isocalendar()[1]%}
  #         {{ ((week_number -1) // 2) % 2 == 0 }}
  # - sensor:
  #     - name: GuttaTemperatur
  #       unique_id: GuttaTemperatur
  #       state: >-
  #         {%set hjemme_uke = states.binary_sensor.erhjemmeuke.state%}
  #         {%if(hjemme_uke == 'on') %}
  #           {%set temp = 18 if now().hour >= 23 else 22 if now().hour >= 16 else 10%}
  #           {{temp}}
  #         {% else %}
  #           {{10}}
  #         {% endif %}
input_number:
  golf_soc_limit:
    name: E-Golf Soc Limit
    initial: 90
    min: 70
    max: 100
    step: 1

automation:
  - id: notifycartocharge
    alias: notifycartocharge
    trigger:
      - platform: time
        at: "21:00:00"
    action:
      - service: script.turn_on
        target:
          entity_id: script.notifymehome
        data_template:
          variables:
            title: "Car to charge tonight"
            message: >-
              {{states('sensor.car_charging')}}
            channel: "cars"

  - alias: ShouldKeepChargingGolf
    id: ShouldKeepChargingGolf
    trigger:
      - platform: state
        entity_id: sensor.garage_status
      - platform: state
        entity_id: sensor.e_golf_battery_level
      - platform: state
        entity_id: binary_sensor.shouldkeepcharginggolf
      - platform: state
        entity_id: input_number.golf_soc_limit
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.e_golf_position
            state: "home"
          - condition: state
            entity_id: binary_sensor.e_golf_charging_cable_connected
            state: "on"
          - condition: state
            entity_id: binary_sensor.modely_charger_sensor
            state: "off"
    action:
      - service: easee.action_command
        data:
          device_id: 6253823754803a08f0b3d8c4d7acbd30
          action_command: "{{'resume' if is_state('binary_sensor.shouldkeepcharginggolf', 'on') else 'pause'}}"

  - alias: Forgot To Lock Golf
    id: forgotToLockGolf
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.forgot_to_lock_golf
        from: "off"
        to: "on"
    action:
      - variables:
          car_lat: "{{ state_attr('device_tracker.e_golf_position', 'latitude') | float }}"
          car_lon: "{{ state_attr('device_tracker.e_golf_position', 'longitude') | float }}"
          erlend_lat: "{{ state_attr('person.erlend', 'latitude') | float }}"
          erlend_lon: "{{ state_attr('person.erlend', 'longitude') | float }}"
          caroline_lat: "{{ state_attr('person.caroline', 'latitude') | float }}"
          caroline_lon: "{{ state_attr('person.caroline', 'longitude') | float }}"
          erlend_distance: "{{ distance(car_lat, car_lon, erlend_lat, erlend_lon) }}"
          caroline_distance: "{{ distance(car_lat, car_lon, caroline_lat, caroline_lon) }}"
          closest_person: "{{ 'erlend' if erlend_distance < caroline_distance else 'caroline' }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ closest_person == 'erlend' }}"
            sequence:
              - service: notify.mobile_app_erlend_mobil
                data:
                  title: "Du glemte å låse Golfen!"
                  message: "Du er nærmest bilen – husk å låse!"
          - conditions:
              - condition: template
                value_template: "{{ closest_person == 'caroline' }}"
            sequence:
              - service: notify.mobile_app_pixel_10_pro
                data:
                  title: "Du glemte å låse Golfen!"
                  message: "Du er nærmest bilen – husk å låse!"
              - service: notify.mobile_app_erlend_mobil
                data:
                  title: "Caroline glemte å låse Golfen!"
                  message: "Aiaiai!"
  - id: e_golf_windhshield_heater_still_on
    alias: e_golf_windhshield_heater_still_on
    trigger:
      - platform: state
        entity_id: switch.e_golf_window_heater
        to: "on"
        for:
          hours: 1
    condition:
      - alias: "not moving"
        condition: state
        entity_id: binary_sensor.e_golf_vehicle_moving
        state: "off"
    action:
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Varmetråder på Golf er fremdeles på
            message: Varmetråder på Golf er fremdeles på
script:
  climate_egolf:
    alias: "Climate E-golf"
    sequence:
      - action: climate.turn_on
        entity_id: climate.e_golf_electric_climatisation
      - action: switch.turn_on
        entity_id:
          - switch.e_golf_window_heater
          #- switch.e_golf_electric_climatisation

          #- switch.e_golf_electric_climatisation
          #- switch.e_golf_auxiliary_climatisation
      # - service: climate.turn_on
      #   data:
      #     entity_id: climate.e_golf_electric_climatisation
      # - service: climate.set_preset_mode
      #   data:
      #     preset_mode: "heat/cool"
      #     entity_id: climate.e_golf_electric_climatisation
      - delay:
          seconds: 30
      - service: switch.turn_on
        entity_id: switch.e_golf_force_data_refresh
      - delay:
          minutes: 3
      - condition: state
        entity_id: sensor.e_golf_request_results
        state: "fail"
      - service: switch.turn_on
        entity_id:
          - switch.e_golf_window_heater
          - switch.e_golf_electric_climatisation

  stop_climate_egolf:
    alias: "Stop Climate E-golf"
    sequence:
      - action: climate.turn_off
        entity_id: climate.e_golf_electric_climatisation
      - service: switch.turn_off
        entity_id:
          - switch.e_golf_window_heater
          - switch.e_golf_electric_climatisation
          #- switch.e_golf_electric_climatisation
          #- switch.e_golf_auxiliary_climatisation
      # - service: climate.turn_off
      #   data:
      #     entity_id: climate.e_golf_electric_climatisation
      # - delay:
      #     seconds: 30
      - service: switch.turn_on
        entity_id: switch.e_golf_force_data_refresh
