input_number:
  grill_temp:
    name: Steketemperatur
    initial: 80
    min: 45
    max: 90
    step: 0.5

automation:
  - id: grill_done
    alias: grill_done
    trigger:
      # template trigger if sensor.grill_1 is over input_number.grill_temp for 2 minutes
      - platform: template
        for:
          minutes: 1
        value_template: >
          {{ states('sensor.grill_1') | float > states('input_number.grill_temp') | float and states('sensor.grill_1') | float < 2000 }}
      - platform: template
        for:
          minutes: 1
        value_template: >
          {{ states('sensor.grill_2') | float > states('input_number.grill_temp') | float and states('sensor.grill_2') | float < 2000}}
    action:
      - service: script.turn_on
        entity_id: script.say
        data_template:
          variables:
            message: "Bonn apetitt! Steketermometeret har en temperatur på {{states.sensor.grill_1.state}} grader"
      - service: script.turn_on
        entity_id: script.notifyboth
        data_template:
          variables:
            title: Middagen er klar!
            message: "Bonn apetitt! Steketermometeret har en temperatur på {{states.sensor.grill_1.state}} grader"
