automation:
  - alias: guestmode_turnOffLightsAndHeating
    trigger:
      - platform: time
        at: "23:59:00"
    condition:
      - condition: state
        entity_id: input_boolean.guestmode
        state: "on"
    action:
      - service: lock.lock
        data:
          entity_id: lock.ytterdor_bluetooth
          code: !secret lock_code

      - entity_id: script.alllightsoff
        service: script.turn_on
      - entity_id: script.alllightsoff
        service: script.turn_on
      - service: switch.turn_off
        entity_id: switch.nexa3 #Fan Heater

  - id: guestmode_lockdoors
    alias: guestmode_lockdoors
    trigger:
      - platform: state
        entity_id: binary_sensor.hoveddor
        to: "off"
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: input_boolean.guestmode
        state: "on"
    action:
      - service: lock.lock
        data:
          entity_id: lock.ytterdor_bluetooth
          code: !secret lock_code

  - alias: Guestmode Notify Movement
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_bedroom
          - binary_sensor.motion_downstairs_office
          - cover.garage_door
        to: "on"
        from: "off"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.erlendhome
          state: "off"
        - condition: state
          entity_id: input_boolean.guestmode
          state: "on"
    action:
      - service: notify.me
        data_template:
          message: "Motion detected in {{ trigger.from_state.name }}."

  - alias: Auto Disable Guestmode
    trigger:
      - platform: state
        entity_id: sensor.alarm
        to: "Disarm"
        from: 
          - "Arm Home"
          - "Arm Away"
          - "Arm Night"
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.guestmode
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guestmode
      - service: notify.me
        data:
          message: "Gjestemodus automatisk slått av fordi du er hjemme og våken."
      - service: script.turn_on
        entity_id: script.notifycaroline
        data:
          variables:
            message: "Gjestemodus automatisk slått av fordi noen er hjemme og våken."
      - service: script.turn_on
        entity_id: script.ai_say
        data:
          prompt: "Gjestemodus er nå slått av."

binary_sensor:
  - platform: template
    scan_interval: 10
    sensors:
      guestmode_activated:
        value_template: >
          {{states.input_boolean.guestmode.state == 'on' and states.sensor.alarm.state != 'Disarm' }}
