automation:
  - alias: "IfttcloseGarage"
    trigger:
      platform: webhook
      webhook_id: !secret ifttclosegarage
      local_only: false
    action:
      - service: cover.close_cover
        entity_id: cover.garage_door
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Garage closed by IFTT.
            message: Garage closed by IFTT.

  - alias: "IfttopenGarage"
    trigger:
      platform: webhook
      webhook_id: !secret ifttopengarage
      local_only: false
    action:
      - service: cover.open_cover
        entity_id: cover.garage_door
      - service: script.turn_on
        entity_id: script.notify
        data_template:
          variables:
            title: Garage opened by IFTT.
            message: Garage opened by IFTT.

  - alias: "ifttBrigthness"
    trigger:
      platform: webhook
      webhook_id: !secret ifttbrigthness
      local_only: false
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.brightness
          value: "{{ (trigger.json.value | float(default=0)) -1}}"
      - service: input_number.set_value
        data_template:
          entity_id: input_number.brightness
          value: "{{ trigger.json.value | float(default=0)}}"

  - alias: "IFTTTurnOffTV"
    trigger:
      platform: webhook
      webhook_id: !secret ifttturnofftv
      local_only: false
    action:
      - service: media_player.turn_off
        entity_id: media_player.tv_stua

  - alias: "IFTTTPauseTV"
    trigger:
      platform: webhook
      webhook_id: !secret pausetviftt
      local_only: false
    action:
      - service: media_player.media_pause
        entity_id: media_player.tv_stua

  - alias: "Run Vacuum IFTT"
    trigger:
      platform: webhook
      webhook_id: !secret runvacuumiftt
      local_only: false
    action:
      - service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: "lockDoorIftt"
    trigger:
      platform: webhook
      webhook_id: !secret lockdooriftt
      local_only: false
    action:
      - service: lock.lock
        entity_id: lock.ytterdor
        data_template:
          code: "{{ trigger.json.value}}"

  - alias: "IFTTturnofflights"
    trigger:
      platform: webhook
      webhook_id: !secret turnofflightsiftt
      local_only: false
    action:
      - service: script.turn_on
        entity_id: script.lightsoff

  - alias: "IFTTturnonlights"
    trigger:
      platform: webhook
      webhook_id: !secret turnonlightsiftt
      local_only: false
    action:
      - service: script.turn_on
        entity_id: script.lightson
