input_datetime:
  maki_inside_time:
    name: "Maki Inside Time"
    has_time: true
    has_date: true

  maki_outside_time:
    name: "Maki Outside Time"
    has_time: true
    has_date: true

input_boolean:
  maki_medisin_gitt:
    name: "Maki har fått medisin"

automation:
  - alias: Notify When Cat Enters or Exits
    id: "notifymakioutsideinside"
    description: Send a notification when the cat goes in or out the door and how long Maki was out or inside
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.maki
        from: "off"
        to: "on"
        id: cat_in
      - platform: state
        entity_id: binary_sensor.maki
        from: "on"
        to: "off"
        id: cat_out
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: cat_in
            sequence:
              # Set the inside timestamp when Maki comes in
              - action: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.maki_inside_time
                data:
                  timestamp: "{{ now().timestamp() }}"
              # Calculate how long Maki was outside
              - variables:
                  #time_outside: "{{ (as_timestamp(now()) - as_timestamp(states('input_datetime.maki_outside_time'))) | int }}"
                  time_outside: "{{ (as_timestamp(now()) - as_timestamp(states('input_datetime.maki_outside_time') | default(now()))) | int }}"
              - action: script.turn_on
                entity_id: script.notifyboth
                data:
                  variables:
                    title: "Maki er inne🏠"
                    message: "Tid: {{ time_outside // 3600 }} timer og {{ (time_outside % 3600) // 60 }} minutter."
                    channel: "cat"
          - conditions:
              - condition: trigger
                id: cat_out
            sequence:
              # Set the outside timestamp when Maki goes out
              - action: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.maki_outside_time
                data:
                  timestamp: "{{ now().timestamp() }}"
              # Calculate how long Maki was inside
              - variables:
                  #time_inside: "{{ (as_timestamp(now()) - as_timestamp(states('input_datetime.maki_inside_time'))) | int }}"
                  time_inside: "{{ (as_timestamp(now()) - as_timestamp(states('input_datetime.maki_inside_time') | default(now()))) | int }}"
              - action: script.turn_on
                entity_id: script.notifyboth
                data:
                  variables:
                    title: "Maki er ute🌲"
                    message: "Tid: {{ time_inside // 3600 }} timer og {{ (time_inside % 3600) // 60 }} minutter."
                    channel: "cat"

  - alias: "Nullstill Maki medisin-onsdag"
    trigger:
      - platform: time
        at: "19:00:00"
    condition:
      - condition: template
        value_template: "{{ now().isoweekday() == 3 }}" # Onsdag
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.maki_medisin_gitt

  - alias: "Varsle om Maki sin medisin ved kjøkkenbesøk"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_kitchen
        to: "on"
      - platform: state
        entity_id: binary_sensor.maki
        to: "on"
    condition:
      # - condition: template
      #   value_template: "{{ now().isoweekday() == 3 and now().hour >= 19 }}"
      - condition: state
        entity_id: binary_sensor.maki # Eksisterende sensor: on = inne
        state: "on"
      - condition: state
        entity_id: input_boolean.maki_medisin_gitt
        state: "off"
    action:
      - service: notify.mobile_app_erlend_mobil
        data:
          title: "Husk Maki sin medisin 💊"
          message: "Maki er inne. Har du gitt henne pillen?"
          data:
            actions:
              - action: MAKI_MEDISIN_GITT
                title: "Har gitt medisin"
      - service: notify.mobile_app_pixel_7_pro
        data:
          title: "Husk Maki sin medisin 💊"
          message: "Maki er inne. Har du gitt henne pillen?"
          data:
            actions:
              - action: MAKI_MEDISIN_GITT
                title: "Har gitt medisin"

  - alias: "Bekreft medisin til Maki via notifikasjon"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: MAKI_MEDISIN_GITT
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.maki_medisin_gitt
      - service: script.notifyboth
        data:
          variables:
            title: "Maki har fått medisin 💊"
            message: "Registrert via mobil-varsling."
