input_boolean:
  takemeds:
    name: Take Medication

automation:
  - alias: TakeMeds
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_kitchen
          - input_boolean.easleep
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.takemeds
          state: "on"
        - condition: state
          entity_id: person.erlend
          state: "home"
        - condition: state
          entity_id: input_boolean.easleep
          state: "off"
          for:
            minutes: 5
    action:
      - service: notify.mobile_app_erlend_mobil
        data:
          message: "remove_channel"
          data:
            channel: "medication"
      - service: notify.mobile_app_erlend_mobil
        data_template:
          title: "Ta Medisin"
          message: "Ta Medisin"
          data:
            channel: "medication"
            ttl: 0
            priority: high
            actions:
              - action: medstaken
                title: Taken!
                destructive: true
      - condition: template
        value_template: "{{ states.media_player.kitchen_display.state != 'playing' and states.media_player.kitchen_display.state != 'paused'}}"
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kitchen_display
          volume_level: "{{states.sensor.speakervolume.state | float(default=0)+ 0.2}}"

      # - service: script.turn_on
      #   entity_id: script.sayaikitchen
      #   data_template:
      #     variables:
      #       message: Erlend må ta medisinen sin
      - service: tts.google_cloud_say
        entity_id: media_player.kitchen_display
        data_template:
          message: "Ta medisin"
      - delay:
          seconds: 10
      - service: media_player.media_stop
        entity_id: media_player.kitchen_display
      - delay:
          minutes: 2

  - alias: TurnOnMeds
    trigger:
      - platform: time
        at: "20:00:00"
      - platform: time
        at: "05:00:00"
      # - platform: state
      #   entity_id: input_boolean.easleep
      #   to: "off"
      #   for:
      #     minutes: 5
    # condition:
    #   - alias: "Not sleeping"
    #     condition: state
    #     entity_id: input_boolean.easleep
    #     state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.takemeds
      # - condition: template
      #   value_template: "{{ states.person.erlend.state != 'home' }}"
      - service: notify.mobile_app_erlend_mobil
        data_template:
          title: "Ta Medisin"
          message: "Ta Medisin"
          data:
            channel: "medication"
            actions:
              - action: medstaken
                title: Taken!
                destructive: true

  - alias: medsTaken
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: medstaken
      - platform: tag
        tag_id: bffa609d-495b-447a-8a04-3df26bb9324b
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.takemeds
