homeassistant:
  customize:
    # Add state-class to enable long term statistics:
    sensor.rammelan_balance:
      state_class: measurement
    sensor.rammelan:
      state_class: measurement
    sensor.brukskonto:
      state_class: measurement
    sensor.bufferkonto:
      state_class: measurement
    sensor.felleskortet:
      state_class: measurement
    sensor.regningskonto:
      state_class: measurement
    sensor.sparekonto:
      state_class: measurement
    sensor.til_betaling:
      state_class: measurement
    sensor.sbanken_egen_cash:
      state_class: measurement
    sensor.sbanken_samlet_cash:
      state_class: measurement

template:
  - sensor:
      - name: "Rammelån balance"
        unit_of_measurement: NOK
        device_class: monetary
        state: >-
          {{ states.sensor.rammelan.attributes.balance }}
      - name: Rammelån Last transaction
        state: >-
          {%set last = states.sensor.rammelan.attributes.transactions[0]%}
          {{last.amount}} på {{last.text}}
      - name: Felleskortet Last transaction
        state: >-
          {%set last = states.sensor.felleskortet.attributes.transactions[0]%}
          {{last.amount}} på {{last.text}}
      - name: Regningskonto Last transaction
        state: >-
          {%set last = states.sensor.regningskonto.attributes.transactions[0]%}
          {{last.amount}} på {{last.text}}
      - name: Sbanken Egen Cash
        unit_of_measurement: NOK
        state_class: measurement
        state: >-
          {%set brukskonto = states('sensor.brukskonto') | float(default=0)%}
          {%set bufferkonto = states('sensor.bufferkonto') | float(default=0)%}
          {%set sparekonto = states('sensor.sparekonto') | float(default=0)%}
          {%set til_betaling = states('sensor.til_betaling') | float(default=0)%}
          {{brukskonto + bufferkonto + sparekonto + til_betaling}}
      - name: Sbanken Samlet Cash
        unit_of_measurement: NOK
        state_class: measurement
        state: >-
          {%set egne_kontoer = states('sensor.sbanken_egen_cash') | float(default=0)%}
          {%set felleskortet = states('sensor.felleskortet') | float(default=0)%}
          {%set rammelan = states('sensor.rammelan') | float(default=0)%}
          {{egne_kontoer + felleskortet + rammelan}}

automation:
  - id: felleskortetlow
    alias: felleskortetlow
    trigger:
      - platform: numeric_state
        entity_id: sensor.felleskortet
        below: 1000
    action:
      - service: script.turn_on
        entity_id: script.notifyboth
        data_template:
          variables:
            title: "Lite penger igjen på felleskortet"
            message: "Disponibel saldo er {{states('sensor.felleskortet') | round(0)}} kroner"

  - id: updaterammelansheets
    alias: updaterammelansheets
    trigger:
      # - platform: state
      #   entity_id: sensor.rammelan_last_transaction
      - platform: template
        value_template: "{{ states.sensor.rammelan.attributes.transactions[0] }}"
    condition:
      - condition: template
        value_template: "{{trigger.to_state.state != ''}}"
      - condition: template
        value_template: "{{trigger.to_state.state != trigger.from_state.state}}"
    action:
      - service: google_sheets.append_sheet
        data:
          config_entry: c24dd893a5b4a2667d24610dc5b5577a
          worksheet: Rammelånbevegelser
          data:
            Dato: "{{states.sensor.rammelan.attributes.transactions[0].accountingDate}}"
            Sum: "{{states.sensor.rammelan.attributes.transactions[0].amount}}"
            Årsak: "{{states.sensor.rammelan.attributes.transactions[0].text}}"
            Fra: Home Assistant - Endre meg
#   - alias: NotifyFelleskortet
#     trigger:
#       - platform: state
#         entity_id: sensor.felleskortet_last_transaction
#     condition:
#       - condition: template
#         value_template: "{{trigger.to_state.state != trigger.from_state.state}}"
#     action:
#       - service: notify.mobile_app_oneplus
#         data_template:
#           title: Nytt trekk på felleskortet
#           message: "{{states('sensor.felleskortet_last_transaction')}}"
#           data:
#             ttl: 0
#             priority: high
