template:
  - sensor:
      - name: "smoke_triggered"
        state: >-
          {%- for entity_id in states.group.smokesensors.attributes.entity_id -%}
              {%set entity = states[entity_id] %}
              {%if entity.state == 'on' %}
                {{entity.name}}, 
              {%endif%}
          {%- endfor %}
automation:
  - alias: smokesensorsunavailable
    trigger:
      platform: state
      entity_id:
        - binary_sensor.smoke_kontoret
        - binary_sensor.smoke_stua
        - binary_sensor.smoke_loftet
      to: "unavailable"
      for:
        minutes: 60
    action:
      - service: notify.me #earlier erlendpush
        data_template:
          title: Røykvarsler utilgjengelig!
          message: Røykvarsleren {{ trigger.from_state.name }} er utilgjengelig!

  - id: smokesensors2
    alias: smokesensors2
    trigger:
      platform: state
      entity_id:
        - binary_sensor.smoke_kontoret
        - binary_sensor.smoke_stua
        - binary_sensor.smoke_loftet
      to: "on"
    action:
      - service: script.turn_on
        entity_id: script.smoketriggered
      - service: lock.unlock
        entity_id: lock.ytterdor_bluetooth

  - alias: Smoke cleared
    trigger:
      platform: state
      entity_id:
        - binary_sensor.smoke_kontoret
        - binary_sensor.smoke_stua
        - binary_sensor.smoke_loftet
      to: "off"
      from: "on"
    action:
      - service: script.turn_off
        entity_id: script.smoketriggered
      - service: script.notifycaroline
        data:
          message: "Smoke cleared"
      - service: notify.me #earlier erlendpush
        data:
          message: "Smoke cleared"
      - service: script.turn_off
        entity_id: script.smoketriggered

  - id: 3dprinteronfire
    alias: 3D-Printer on fire
    trigger:
      platform: state
      entity_id: binary_sensor.smoke_kontoret
      to: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.3d_printer_failsafe

script:
  smoketriggered:
    alias: Smoke Triggered
    sequence:
      - service: switch.turn_off
        entity_id: switch.blanket
      #spill av denne flere ganger.
      # - service: xiaomi_aqara.play_ringtone
      #   data:
      #     gw_mac: 7C:49:EB:1C:2D:6B
      #     ringtone_id: 1
      #     ringtone_vol: 100
      # - service: light.turn_on
      #   entity_id: light.gateway_light_7c49eb1c2d6b
      #   data:
      #     color_name: red
      - service: notify.me #earlier erlendpush
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: script.notifycaroline
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: notify.me
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: notify.me #earlier erlendpush
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: script.notifycaroline
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: script.notifycaroline
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: notify.me #earlier erlendpush
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: script.notifycaroline
        data_template:
          title: Alarm!
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker
          volume_level: 1
      - service: tts.google_cloud_say
        entity_id:
          - media_player.minis
          - media_player.clock
        data_template:
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - delay:
          seconds: 5
          #varsler bare en gang.
      - service: tts.google_cloud_say
        entity_id:
          - media_player.minis
          - media_player.clock
        data_template:
          message: Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. '
      - delay:
          seconds: 5
      - service: tts.google_cloud_say
        entity_id:
          - media_player.minis
          - media_player.clock
        data_template:
          message: "Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. "
      - delay:
          seconds: 5
      - service: tts.google_cloud_say
        entity_id:
          - media_player.minis
          - media_player.clock
        data_template:
          message: "Røykvarsler {{states.sensor.smoke_triggered.state}} utløst! {{states.sensor.peoplehome.state}} er hjemme. "
      - delay:
          seconds: 12
      - service: media_player.volume_set
        data_template:
          entity_id:
            - media_player.minis
            - media_player.clock
          volume_level: 0.5
      # - service: xiaomi_aqara.play_ringtone
      #   data:
      #     gw_mac: 7C:49:EB:1C:2D:6B
      #     ringtone_id: 1
      #     ringtone_vol: 100
      # - service: light.turn_off
      #   entity_id: light.gateway_light_7c49eb1c2d6b
