template:
  - sensor:
      - name: "smoke_triggered"
        state: >-
          {%- for entity_id in states.group.smokesensors.attributes.entity_id -%}
              {%set entity = states[entity_id] %}
              {%if entity.state == 'on' %}
                {{entity.name}}, 
              {%endif%}
          {%- endfor %}
automation:
  - id: smokesensorsunavailable
    alias: "Røykvarsler utilgjengelig"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.smoke_kontoret
          - binary_sensor.smoke_stua
          - binary_sensor.smoke_loftet
        to: "unavailable"
        for:
          minutes: 60
    action:
      - service: script.notifyboth
        data:
          title: "⚠️ Røykvarsler utilgjengelig!"
          message: "Røykvarsleren {{ trigger.from_state.name }} er utilgjengelig!"

  - id: smokesensors2
    alias: "Røykvarsler utløst"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.smoke_kontoret
          - binary_sensor.smoke_stua
          - binary_sensor.smoke_loftet
        to: "on"
    action:
      - service: script.turn_on
        target:
          entity_id: script.smoketriggered

  - id: smoke_cleared
    alias: "Røyk klarert"
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {{ expand('group.smokesensors') | selectattr('state', 'eq', 'on') | list | count == 0 }}
    condition:
      - condition: state
        entity_id: script.smoketriggered
        state: "on"
    action:
      - service: script.turn_off
        target:
          entity_id: script.smoketriggered
      - service: media_player.media_stop
        target:
          entity_id:
            - media_player.minis
            - media_player.clock
            - media_player.living_room_speaker
            - media_player.hallway_speaker
            - media_player.bathroom
            - media_player.kitchen_display
      - service: tts.google_cloud_say
        target:
          entity_id:
            - media_player.minis
            - media_player.clock
            - media_player.living_room_speaker
            - media_player.hallway_speaker
            - media_player.bathroom
            - media_player.kitchen_display
        data:
          message: "Faren er over. Alle røykvarslere er nå stille."
      - service: script.notifyboth
        data:
          title: "✅ Røyk klarert"
          message: "Alle røykvarslere er nå stille."

  - id: 3dprinteronfire
    alias: "3D-Printer brannvern"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.smoke_kontoret
        to: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.3d_printer_failsafe

script:
  smoketriggered:
    alias: Smoke Triggered
    mode: restart
    sequence:
      - variables:
          smoke_message: "BRANNALARM! Røykvarsler {{ states('sensor.smoke_triggered') }} utløst!"
      # Umiddelbare tiltak
      - parallel:
          - service: switch.turn_off
            target:
              entity_id: switch.blanket
          - service: lock.unlock
            target:
              entity_id: lock.ytterdor_bluetooth
      # Første varsling til alle kanaler
      - parallel:
          - service: script.notifyboth
            data:
              title: "🔥 BRANNALARM!"
              message: "{{ smoke_message }}"
              channel: alarm_stream_max
          - service: script.notify_tts_max
            data:
              message: "{{ smoke_message }}"
      # Loop så lenge røyk er detektert
      - repeat:
          while:
            - condition: template
              value_template: >-
                {{ expand('group.smokesensors') | selectattr('state', 'eq', 'on') | list | count > 0 }}
          sequence:
            # Sørg for at høyttalerne er ledige før ny varsling
            - service: media_player.media_stop
              continue_on_error: true
              target:
                entity_id:
                  - media_player.minis
                  - media_player.clock
                  - media_player.living_room_speaker
                  - media_player.hallway_speaker
                  - media_player.bathroom
                  - media_player.kitchen_display
            # Sett volum til maks på alle høyttalere
            - service: media_player.volume_set
              continue_on_error: true
              target:
                entity_id:
                  - media_player.minis
                  - media_player.clock
                  - media_player.living_room_speaker
                  - media_player.hallway_speaker
                  - media_player.bathroom
                  - media_player.kitchen_display
              data:
                volume_level: 1
            # TTS-varsling på alle høyttalere
            - service: tts.google_cloud_say
              continue_on_error: true
              target:
                entity_id:
                  - media_player.minis
                  - media_player.clock
                  - media_player.living_room_speaker
                  - media_player.hallway_speaker
                  - media_player.bathroom
                  - media_player.kitchen_display
              data:
                message: "{{ smoke_message }}"
            - delay:
                seconds: 4
            - service: media_player.play_media
              continue_on_error: true
              target:
                entity_id:
                  - media_player.minis
                  - media_player.clock
                  - media_player.living_room_speaker
                  - media_player.hallway_speaker
                  - media_player.bathroom
                  - media_player.kitchen_display
              data:
                media_content_id: "https://hjem.sellie.no/local/sounds/screams/airraid.mp3"
                media_content_type: "music"
            - delay:
                seconds: 12
            # Push-varsling hver 3. iterasjon
            - if:
                - condition: template
                  value_template: "{{ repeat.index % 3 == 0 }}"
              then:
                - service: script.notifyboth
                  data:
                    title: "🔥 BRANNALARM FORTSETTER!"
                    message: "{{ smoke_message }} (Varsling #{{ repeat.index }})"
                    channel: alarm_stream_max
      # Når loopen er ferdig, sett volum tilbake
      - service: media_player.volume_set
        continue_on_error: true
        target:
          entity_id:
            - media_player.minis
            - media_player.clock
            - media_player.living_room_speaker
            - media_player.hallway_speaker
            - media_player.bathroom
            - media_player.kitchen_display
        data:
          volume_level: 0.5
