automation:
  - alias: stian_sover_on
    trigger:
      - platform: state
        entity_id: binary_sensor.stian_is_charging
        to: "on"
    condition:
      - condition: time
        after: "21:30:00"
        before: "06:00:00"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.stianasleep

  - alias: stian_sover_off
    trigger:
      - platform: state
        entity_id: binary_sensor.stian_is_charging
        to: "off"
    condition:
      - condition: time
        after: "04:00:00"
        before: "14:00:00"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.stianasleep
