automation:
  - alias: UpstairsDoorLeftOpen
    id: UpstairsDoorLeftOpen
    trigger:
      # - platform: state
      #   entity_id: binary_sensor.trymdoorleftopen
      #   to: "on"
      #SENSOR NOT WORKING..
      # - platform: state
      #   entity_id: binary_sensor.bathroomleftopen
      #   to: "on"
      # - platform: state
      #   entity_id: binary_sensor.tyradoorleftopen
      #   to: "on"
    condition:
      - condition: state
        entity_id: person.caroline
        state: "home"
      - condition: numeric_state
        entity_id: sensor.ute_temperature
        below: 3
    action:
      repeat:
        while:
          - condition: template
            value_template: "{{states[trigger.entity_id].state  == 'on'}}"
          - condition: state
            entity_id: input_select.alarm
            state: "Disarm"
        sequence:
          - service: script.turn_on
            entity_id: script.notifyhome
            data_template:
              variables:
                title: Dør åpen
                message: "{{trigger.from_state.name}}"
          - condition: template
            value_template: "{{states('binary_sensor.google_home_playing') != 'on'}}"
          # - service: media_player.volume_set
          #   data_template:
          #     entity_id: media_player.hallway_speaker
          #     volume_level: "{{0.4}}"
          # - service: media_player.volume_set
          #   data_template:
          #     entity_id: media_player.living_room_speaker
          #     volume_level: "{{0.4}}"
          - service: media_player.play_media
            data:
              entity_id: media_player.minis
              media_content_id: "https://hjem.sellie.no/local/sounds/korok.mp3"
              media_content_type: "music"
          - delay:
              seconds: 3
          - service: media_player.volume_set
            data_template:
              entity_id: media_player.minis
              volume_level: "{{states.sensor.speakervolume.state}}"
          - delay:
              minutes: 10

template:
  - binary_sensor:
      - name: "stairsexposed"
        unique_id: stairsexposed_sensor
        device_class: opening
        state: >-
          {{ (states.binary_sensor.grind.state == 'on' and states.group.innedorsensorer.state == 'on')
          and ((states.input_boolean.trymasleep.state == 'off' and states.binary_sensor.trym_home.state == 'on') 
          or (states.input_boolean.tyraasleep.state == 'off' and states.binary_sensor.tyra_home.state == 'on')) }}

      - name: "upstairstairs"
        unique_id: upstairstairs_sensor
        device_class: opening
        state: "{{ states.binary_sensor.grind_oppe.state == 'on' and states.binary_sensor.tyra_home.state == 'on' and states.input_boolean.tyraasleep.state == 'on' }}"

      - name: "bathroomleftopen"
        unique_id: bathroomleftopen_sensor
        device_class: opening
        delay_on:
          minutes: 5
        state: >-
          {{ states.binary_sensor.motionupstairs.state == 'off' and
          states.binary_sensor.door_bathroom.state == 'on' }}

      - name: "trymdoorleftopen"
        unique_id: trymdoorleftopen_sensor
        device_class: opening
        delay_on:
          minutes: 5
        state: >-
          {{ states.binary_sensor.motionupstairs.state == 'off' and
          states.binary_sensor.trym_door.state == 'on' and
          states.input_boolean.trymasleep.state == 'off' }}

      - name: "tyradoorleftopen"
        unique_id: tyradoorleftopen_sensor
        device_class: opening
        delay_on:
          minutes: 5
        state: >-
          {{ states.binary_sensor.motionupstairs.state == 'off' and
          states.binary_sensor.tyra_door.state == 'on' and
          states.input_boolean.tyraasleep.state == 'off' }}
