input_boolean:
  vacuum_just_emptied:
    name: Vacuum just emptied

automation:
  - alias: "cleandustbin"
    trigger:
      platform: webhook
      webhook_id: !secret cleanthedustbin
      local_only: false
      allowed_methods:
        - POST
        - PUT
    action:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.cleandustbin

  - alias: SendToKitchen
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_kitchen
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - thu
            - sat
        - condition: state
          entity_id: input_boolean.vacuum_just_emptied
          state: "off"
        - condition: template
          value_template: "{{ states('input_select.alarm') == 'Disarm'}}"
        - condition: template
          value_template: "{{ states('media_player.living_room_tv') != 'playing'}}"
        - condition: time
          after: "12:00:00"
    action:
      - action: vacuum.stop
        target:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - action: script.turn_on
        target:
          entity_id: script.sendvacuumtokitchen
      # - service: vacuum.send_command
      #   data:
      #     entity_id: vacuum.xiaomi_vacuum_cleaner
      #     command: app_goto_target
      #     params: [25000,32800]
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacuum_just_emptied
      - action: script.turn_on
        target:
          entity_id: script.say
        data:
          message: "Tøm Svetlana."

  - alias: VaccumJustEmptiedNot
    trigger:
      - platform: time
        at: "12:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_just_emptied
        state: "on"
    action:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacuum_just_emptied

  - id: vacuum_return_home_when_idle_or_stuck
    alias: "Vacuum return home when idle/stuck"
    mode: single
    trigger:
      - id: idle_30
        platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: "idle"
        for:
          minutes: 30
      - id: stuck_30
        platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: "error"
        for:
          minutes: 30
      - id: alarm_changed
        platform: state
        entity_id: input_select.alarm
    condition:
      - condition: state
        entity_id: input_select.alarm
        state:
          - "Arm Away"
          - "Disarm"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - idle_30
                  - stuck_30
            sequence:
              - action: script.turn_on
                target:
                  entity_id: script.dockvacuum
          - conditions:
              - condition: trigger
                id: alarm_changed
              - condition: or
                conditions:
                  - condition: state
                    entity_id: vacuum.xiaomi_vacuum_cleaner
                    state: "idle"
                    for:
                      minutes: 30
                  - condition: state
                    entity_id: vacuum.xiaomi_vacuum_cleaner
                    state: "stuck"
                    for:
                      minutes: 30
            sequence:
              - action: script.turn_on
                target:
                  entity_id: script.dockvacuum

template:
  - sensor:
      - name: "vacuum_battery"
        unique_id: vacuum_battery_sensor
        unit_of_measurement: "%"
        state: >-
          {% if state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') is not none and state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') != '' %}
            {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }}
          {% else %}
            unknown
          {% endif %}
        availability: >-
          {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') is not none and state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') != '' }}

script:
  sendvacuumtokitchen:
    alias: "Send Svetlana to kitchen"
    sequence:
      - action: vacuum.stop
        target:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - action: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_goto_target
          params: [28800, 24150]

  dockvacuum:
    alias: "Send Svetlana to Dock"
    sequence:
      - action: vacuum.return_to_base
        target:
          entity_id: vacuum.xiaomi_vacuum_cleaner

  vacuum_living_room:
    alias: "Vacuum the Living Room"
    sequence:
      - action: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[16119, 22490, 26169, 32190, 2]]

  vacuum_kitchen:
    alias: "Vacuum the Kitchen"
    sequence:
      - action: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[25099, 28207, 29799, 31207, 2]]

  #with broadlink remote on old Roomba
  # startroomba:
  #   sequence:
  #     # - service: switch.turn_on
  #     #   entity_id: switch.roomba
  #     - service: switch.broadlink_send_packet_192_168_1_239
  #       data:
  #         packet:
  #           - "JgCkAFsgHF0cXRxdWiEcXRtdHAACfVsgHFseXRxdWiEcXRxcHAACfVshHFwcXRxdWyAcXRxdHAACfFshHFwcXRxdWyAcXRxdHAACfFshHFwcXRxdWyAcXRxdHAACfFshHFwcXRxdWyAcXRxcHAACfVsgHF0cXRxcWyEcXBxdHAACfVsgHF0cXBxdWyAcXRxdHAACfVohHF0cXBxdWyAcXRxdHIwNAA0FAAAAAA=="

  # stoproomba:
  #   sequence:
  #     - service: switch.broadlink_send_packet_192_168_1_239
  #       data:
  #         packet:
  #           - "JgCiAFohHF0cXRxcHVtcIB1cWwACRlohHF0cXRxcHVxbIRxcWwACRlohHF0cXB1cHF1bIBxdWwACRVsgHF0cXRxdHFpdIRxcWwACRVsgHVwcWx5dHFxbIRxcWwACRVsgHVwcXRxdHFxbIRxcWwACRVsgHVwcXRxcHVxbIB1cWwACRVohHF0cXRxcHF1bIBxdWwACRVsgHF0cXRxcHVxbIB1cWwANBQAAAAAAAA=="
