template:
  - binary_sensor:
      - name: "Z2M Devices Unavailable"
        delay_off:
          minutes: 5 #z2m-problem below
        state: >-
          {% set found = namespace(found=false) %}
          {%-for item in states.sensor if (item.attributes.linkquality is defined)-%}
          {%set name = item.attributes.friendly_name%}
          {%-if item.attributes.linkquality | float(default=0) < 1
          and 'Smoke' not in name
          and 'Cube' not in name
          and 'Water' not in name
          -%}
          {%set found.found = true%}
          {%endif%}
          {%- endfor -%}
          {{found.found}}
  - binary_sensor:
      - name: "Z2M Lights Unavailable"
        delay_on:
          minutes: 1
        state: >-
          {{states.light.tvsone.state == 'unknown' or states.light.tvsone.state == 'unavailable'}}

automation:
  - alias: "Z2mDeviceUnavailable"
    id: "Z2mDeviceUnavailable"
    trigger:
      - platform: state
        entity_id: binary_sensor.z2m_devices_unavailable
        to: "on"
    action:
      - service: notify.me #z2m-problem below
        data_template:
          message: >-
            Zigbee Device unavailable?:  
            {%-for item in states.sensor if (item.attributes.linkquality is defined)-%}
            {%set name = item.attributes.friendly_name%}
            {%-if item.attributes.linkquality | float(default=0) < 1
            and 'Smoke' not in name
            and 'Cube' not in name
            and 'Water' not in name-%}
              {{-item.attributes.friendly_name-}} , 
            {%endif%}
            {%- endfor -%}

  - alias: "Z2mLightsUnavailable"
    id: "Z2mLightsUnavailable"
    trigger:
      - platform: state
        entity_id: binary_sensor.z2m_lights_unavailable
        to: "on"
    action:
      - service: notify.me
        data_template:
          message: >-
            Zigbee Lights unavailable?
      - service: hassio.addon_restart
        data:
          addon: "45df7312_zigbee2mqtt"
      #todo wait for trigger to on again
